export const DEMO_ARTISANS = [
  {
    "id": "artisan-001",
    "legacyId": "artisan-1",
    "code": "ART-001",
    "pehchanId": "BR-MAD-PNT-4402",
    "giRegistrationNo": "GI-AU-2018-8421",
    "name": "Savita Devi",
    "gender": "Female",
    "photo": "/images/savita_devi.jpg",
    "craft": "Madhubani Painting",
    "category": "Painting & Wall Art",
    "location": "Ranti Village, Madhubani",
    "state": "Bihar",
    "district": "Madhubani",
    "cluster": "Mithila Painting Megacluster",
    "specialization": "Kohbar & Aripan motifs with natural organic pigments",
    "experience": "18 Years of Traditional Painting",
    "experienceYears": 18,
    "capacity": "40 pieces/month",
    "capacityPerMonth": 40,
    "fulfillmentDays": 7,
    "trustScore": 94,
    "rating": 4.9,
    "reviewCount": 96,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Mithila Mahila Vikas Samiti",
    "phone": "+91 94312 XXXXX",
    "email": "savita.devi@karigarsetu.in",
    "bio": "State-awarded Mithila folk artist with 18 years dedicated to Kohbar and Aripan motifs on handmade paper and tussar silk using natural pigments made from leaves and flowers.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/savita_devi.jpg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Madhubani Painting",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2018-8421)",
      "Ministry of Textiles Pehchan Card (BR-MAD-PNT-4402)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-001",
    "isDemoData": true
  },
  {
    "id": "artisan-002",
    "legacyId": "artisan-2",
    "code": "ART-002",
    "pehchanId": "JH-RAN-MET-6105",
    "giRegistrationNo": "GI-AU-2019-3312",
    "name": "Meena Kumari",
    "gender": "Female",
    "photo": "/images/meena_kumari.jpg",
    "craft": "Dokra Metal Craft",
    "category": "Metal Craft",
    "location": "Torpa, Khunti",
    "state": "Jharkhand",
    "district": "Khunti",
    "cluster": "Chotanagpur Tribal Metal Cluster",
    "specialization": "Non-ferrous lost-wax bell metal casting of figurines and diya oil lamps",
    "experience": "15 Years of Lost-Wax Metal Casting",
    "experienceYears": 15,
    "capacity": "50 pieces/month",
    "capacityPerMonth": 50,
    "fulfillmentDays": 10,
    "trustScore": 92,
    "rating": 4.8,
    "reviewCount": 78,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Birsa Munda Karigar Samiti",
    "phone": "+91 98351 XXXXX",
    "email": "meena.kumari@karigarsetu.in",
    "bio": "Hereditary Dokra metalsmith handcrafting beeswax thread models over clay cores and casting in recycled brass bell metal using indigenous charcoal pit kilns.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/meena_kumari.jpg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Dokra Metal Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2019-3312)",
      "Ministry of Textiles Pehchan Card (JH-RAN-MET-6105)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-002",
    "isDemoData": true
  },
  {
    "id": "artisan-003",
    "legacyId": "artisan-3",
    "code": "ART-003",
    "pehchanId": "UP-BRS-MRD-7811",
    "giRegistrationNo": "GI-AU-2016-1044",
    "name": "Ramesh Kumar",
    "gender": "Male",
    "photo": "/images/ramesh_kumar.svg",
    "craft": "Brass Handicraft",
    "category": "Metal Craft",
    "location": "Peetal Nagri, Moradabad",
    "state": "Uttar Pradesh",
    "district": "Moradabad",
    "cluster": "Moradabad Peetal Nagri Megacluster",
    "specialization": "Hand-turned brass diya lamps, ceremonial urlis, and engraved home accents",
    "experience": "22 Years of Master Brass Art",
    "experienceYears": 22,
    "capacity": "75 pieces/month",
    "capacityPerMonth": 75,
    "fulfillmentDays": 8,
    "trustScore": 95,
    "rating": 4.9,
    "reviewCount": 112,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Peetal Udyog Samiti",
    "phone": "+91 94121 XXXXX",
    "email": "ramesh.kumar@karigarsetu.in",
    "bio": "Third-generation master metalsmith specializing in traditional hand-turned and engraved pure brass festive oil lamps, decorative urlis, and heirloom artefacts in Moradabad.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/ramesh_kumar.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Brass Handicraft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2016-1044)",
      "Ministry of Textiles Pehchan Card (UP-BRS-MRD-7811)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-003",
    "isDemoData": true
  },
  {
    "id": "artisan-004",
    "legacyId": "artisan-4",
    "code": "ART-004",
    "pehchanId": "WB-TER-PAN-1140",
    "giRegistrationNo": "GI-AU-2018-2234",
    "name": "Mohan Das",
    "gender": "Male",
    "photo": "/images/mohan_das.svg",
    "craft": "Terracotta Craft",
    "category": "Pottery & Ceramics",
    "location": "Panchmura, Bankura",
    "state": "West Bengal",
    "district": "Bankura",
    "cluster": "Bankura Terracotta Cluster",
    "specialization": "Bankura Horses, decorative pottery, and architectural terracotta plaques",
    "experience": "15 Years of Traditional Terracotta",
    "experienceYears": 15,
    "capacity": "80 pieces/month",
    "capacityPerMonth": 80,
    "fulfillmentDays": 8,
    "trustScore": 91,
    "rating": 4.8,
    "reviewCount": 64,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Panchmura Terracotta Samiti",
    "phone": "+91 97321 XXXXX",
    "email": "mohan.das@karigarsetu.in",
    "bio": "Master Kumbhakar potter hand-shaping distinctive Bankura horses with erect ears and hollow symmetrical terracotta vessels fired in traditional open wood kilns in Panchmura village.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/mohan_das.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Terracotta Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2018-2234)",
      "Ministry of Textiles Pehchan Card (WB-TER-PAN-1140)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-004",
    "isDemoData": true
  },
  {
    "id": "artisan-005",
    "legacyId": "artisan-5",
    "code": "ART-005",
    "pehchanId": "OD-BAR-IKT-5511",
    "giRegistrationNo": "GI-AU-2017-4481",
    "name": "Anjali Sahu",
    "gender": "Female",
    "photo": "/images/avatars/artisan-005.svg",
    "craft": "Sambalpuri Textile",
    "category": "Handloom & Textiles",
    "location": "Bargarh",
    "state": "Odisha",
    "district": "Bargarh",
    "cluster": "Western Odisha Handloom Cluster",
    "specialization": "Tie-and-dye bandha weaving on pit looms using mercerized cotton",
    "experience": "16 Years of Bandha Weaving",
    "experienceYears": 16,
    "capacity": "35 pieces/month",
    "capacityPerMonth": 35,
    "fulfillmentDays": 14,
    "trustScore": 93,
    "rating": 4.9,
    "reviewCount": 88,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Maa Samaleswari Weavers Co-op",
    "phone": "+91 94371 XXXXX",
    "email": "anjali.sahu@karigarsetu.in",
    "bio": "Hereditary Bhulia Meher master weaver crafting intricate ikat motifs representing traditional shankha, chakra, and flora without any printed chemical dyes.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-005.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Sambalpuri Textile",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2017-4481)",
      "Ministry of Textiles Pehchan Card (OD-BAR-IKT-5511)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-005",
    "isDemoData": true
  },
  {
    "id": "artisan-006",
    "legacyId": "artisan-6",
    "code": "ART-006",
    "pehchanId": "OD-PURI-PAT-3310",
    "giRegistrationNo": "GI-AU-2015-7712",
    "name": "Arjun Sahu",
    "gender": "Male",
    "photo": "/images/avatars/artisan-006.svg",
    "craft": "Pattachitra",
    "category": "Painting & Wall Art",
    "location": "Raghurajpur, Puri",
    "state": "Odisha",
    "district": "Puri",
    "cluster": "Raghurajpur Heritage Craft Village",
    "specialization": "Traditional cloth scroll painting depicting Jagannath & mythological themes",
    "experience": "24 Years of Pattachitra",
    "experienceYears": 24,
    "capacity": "25 pieces/month",
    "capacityPerMonth": 25,
    "fulfillmentDays": 15,
    "trustScore": 96,
    "rating": 5,
    "reviewCount": 120,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Chitrakar Mahasangha",
    "phone": "+91 94378 XXXXX",
    "email": "arjun.sahu@karigarsetu.in",
    "bio": "Master chitrakar preparing cloth canvas with chalk and tamarind gum and painting with stone and conch shell pigments.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-006.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Pattachitra",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2015-7712)",
      "Ministry of Textiles Pehchan Card (OD-PURI-PAT-3310)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-006",
    "isDemoData": true
  },
  {
    "id": "artisan-007",
    "legacyId": "artisan-7",
    "code": "ART-007",
    "pehchanId": "BR-DAR-SIK-1029",
    "giRegistrationNo": "GI-AU-2020-5512",
    "name": "Pooja Mahato",
    "gender": "Female",
    "photo": "/images/avatars/artisan-007.svg",
    "craft": "Bamboo & Cane Craft",
    "category": "Natural Fibre Craft",
    "location": "Raiyam, Darbhanga",
    "state": "Bihar",
    "district": "Darbhanga",
    "cluster": "North Bihar Sikki Craft Cluster",
    "specialization": "Golden grass decorative boxes, coasters, and storage bins",
    "experience": "8 Years of Fiber Craft",
    "experienceYears": 8,
    "capacity": "60 pieces/month",
    "capacityPerMonth": 60,
    "fulfillmentDays": 7,
    "trustScore": 89,
    "rating": 4.7,
    "reviewCount": 42,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Kalyani Gramin SHG",
    "phone": "+91 94301 XXXXX",
    "email": "pooja.mahato@karigarsetu.in",
    "bio": "Young artisan co-operative leader transforming wetland wild grasses into moisture-resistant sustainable kitchenware and lifestyle baskets.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-007.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Bamboo & Cane Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2020-5512)",
      "Ministry of Textiles Pehchan Card (BR-DAR-SIK-1029)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-007",
    "isDemoData": true
  },
  {
    "id": "artisan-008",
    "legacyId": "artisan-8",
    "code": "ART-008",
    "pehchanId": "CG-BAS-IRO-4419",
    "giRegistrationNo": "GI-AU-2018-9901",
    "name": "Rajesh Mahato",
    "gender": "Male",
    "photo": "/images/avatars/artisan-008.svg",
    "craft": "Wrought Iron Craft",
    "category": "Metal Craft",
    "location": "Kondagaon, Bastar",
    "state": "Chhattisgarh",
    "district": "Bastar",
    "cluster": "Bastar Tribal Blacksmith Cluster",
    "specialization": "Blacksmith forge metallurgy creating deer, candle stands, and tribal totems",
    "experience": "19 Years of Forge Work",
    "experienceYears": 19,
    "capacity": "65 pieces/month",
    "capacityPerMonth": 65,
    "fulfillmentDays": 9,
    "trustScore": 92,
    "rating": 4.8,
    "reviewCount": 67,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Ghadwa Iron Artisans Guild",
    "phone": "+91 97521 XXXXX",
    "email": "rajesh.mahato@karigarsetu.in",
    "bio": "Uses traditional coal forges and hand tongs to shape scrap scrap iron into minimalist tribal animal sculptures with rust-resistant finishes.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-008.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Wrought Iron Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2018-9901)",
      "Ministry of Textiles Pehchan Card (CG-BAS-IRO-4419)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-008",
    "isDemoData": true
  },
  {
    "id": "artisan-009",
    "legacyId": "artisan-9",
    "code": "ART-009",
    "pehchanId": "WB-BIR-KAN-8802",
    "giRegistrationNo": "GI-AU-2016-3390",
    "name": "Rekha Kumari",
    "gender": "Female",
    "photo": "/images/avatars/artisan-009.svg",
    "craft": "Embroidery",
    "category": "Handloom & Textiles",
    "location": "Bolpur, Shantiniketan",
    "state": "West Bengal",
    "district": "Birbhum",
    "cluster": "Shantiniketan Rural Craft Center",
    "specialization": "Running stitch kantha embroidered silk dupattas and bedspreads",
    "experience": "14 Years of Kantha",
    "experienceYears": 14,
    "capacity": "45 pieces/month",
    "capacityPerMonth": 45,
    "fulfillmentDays": 12,
    "trustScore": 93,
    "rating": 4.9,
    "reviewCount": 82,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Bolpur Kantha Shilpa Samiti",
    "phone": "+91 94340 XXXXX",
    "email": "rekha.kumari@karigarsetu.in",
    "bio": "Organizes a collective of 30 village women hand-stitching traditional folk motifs depicting rural Bengali pastoral life.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-009.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Embroidery",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2016-3390)",
      "Ministry of Textiles Pehchan Card (WB-BIR-KAN-8802)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-009",
    "isDemoData": true
  },
  {
    "id": "artisan-010",
    "legacyId": "artisan-10",
    "code": "ART-010",
    "pehchanId": "RJ-JAI-BLU-2291",
    "giRegistrationNo": "GI-AU-2015-1102",
    "name": "Suresh Prasad",
    "gender": "Male",
    "photo": "/images/avatars/artisan-010.svg",
    "craft": "Blue Pottery",
    "category": "Pottery & Ceramics",
    "location": "Kot Jewar, Jaipur",
    "state": "Rajasthan",
    "district": "Jaipur",
    "cluster": "Jaipur Traditional Blue Pottery Cluster",
    "specialization": "Non-clay quartz powder glazed decorative plates, tiles, and door knobs",
    "experience": "21 Years of Blue Pottery",
    "experienceYears": 21,
    "capacity": "90 pieces/month",
    "capacityPerMonth": 90,
    "fulfillmentDays": 8,
    "trustScore": 95,
    "rating": 4.9,
    "reviewCount": 110,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Jaipur Ceramic Karigar Union",
    "phone": "+91 94140 XXXXX",
    "email": "suresh.prasad@karigarsetu.in",
    "bio": "Formulates indigenous Egyptian paste made from quartz stone, glass, fullers earth, and gum with cobalt oxide blue glazes.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-010.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Blue Pottery",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2015-1102)",
      "Ministry of Textiles Pehchan Card (RJ-JAI-BLU-2291)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-010",
    "isDemoData": true
  },
  {
    "id": "artisan-011",
    "legacyId": "artisan-11",
    "code": "ART-011",
    "pehchanId": "JH-HAZ-MUR-7721",
    "giRegistrationNo": "GI-AU-2020-8844",
    "name": "Sunita Oraon",
    "gender": "Female",
    "photo": "/images/avatars/artisan-011.svg",
    "craft": "Tribal Wall Art",
    "category": "Painting & Wall Art",
    "location": "Bhelwara, Hazaribagh",
    "state": "Jharkhand",
    "district": "Hazaribagh",
    "cluster": "Hazaribagh Indigenous Art Cluster",
    "specialization": "Mural paintings on mud and handmade paper celebrating crop harvest and animal deities",
    "experience": "13 Years of Tribal Art",
    "experienceYears": 13,
    "capacity": "30 pieces/month",
    "capacityPerMonth": 30,
    "fulfillmentDays": 10,
    "trustScore": 90,
    "rating": 4.8,
    "reviewCount": 51,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Hazaribagh Tribal Women Guild",
    "phone": "+91 98356 XXXXX",
    "email": "sunita.oraon@karigarsetu.in",
    "bio": "Paints with natural earth pigments like yellow ocher, red iron stone, and charcoal using twigs and chewed rice straw.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-011.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Tribal Wall Art",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2020-8844)",
      "Ministry of Textiles Pehchan Card (JH-HAZ-MUR-7721)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-011",
    "isDemoData": true
  },
  {
    "id": "artisan-012",
    "legacyId": "artisan-12",
    "code": "ART-012",
    "pehchanId": "KA-RAM-TOY-4411",
    "giRegistrationNo": "GI-AU-2016-5520",
    "name": "Deepak Oraon",
    "gender": "Male",
    "photo": "/images/avatars/artisan-012.svg",
    "craft": "Handmade Toys",
    "category": "Wood Carving",
    "location": "Channapatna, Ramanagara",
    "state": "Karnataka",
    "district": "Ramanagara",
    "cluster": "Channapatna Lacquer Toy Megacluster",
    "specialization": "Turned Wrightia tinctoria (Aale mara) wood toys with non-toxic vegetable lacquer polish",
    "experience": "17 Years of Lacquer Wood Craft",
    "experienceYears": 17,
    "capacity": "120 pieces/month",
    "capacityPerMonth": 120,
    "fulfillmentDays": 6,
    "trustScore": 94,
    "rating": 4.9,
    "reviewCount": 95,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Gombegala Ooru Artisans Society",
    "phone": "+91 98451 XXXXX",
    "email": "deepak.oraon@karigarsetu.in",
    "bio": "Creates child-safe smooth wooden stacking rings, pull-along animals, and educational Montessori toys using natural turmeric and indigo colors.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-012.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Handmade Toys",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2016-5520)",
      "Ministry of Textiles Pehchan Card (KA-RAM-TOY-4411)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-012",
    "isDemoData": true
  },
  {
    "id": "artisan-013",
    "legacyId": "artisan-13",
    "code": "ART-013",
    "pehchanId": "BR-PAT-APP-3319",
    "giRegistrationNo": "GI-AU-2017-9011",
    "name": "Kavita Das",
    "gender": "Female",
    "photo": "/images/avatars/artisan-013.svg",
    "craft": "Khatwa Applique Craft",
    "category": "Handloom & Textiles",
    "location": "Danapur, Patna",
    "state": "Bihar",
    "district": "Patna",
    "cluster": "Magadh Textile Craft Cluster",
    "specialization": "Cut-work fabric applique panels and festive wall hangings",
    "experience": "11 Years of Applique Work",
    "experienceYears": 11,
    "capacity": "50 pieces/month",
    "capacityPerMonth": 50,
    "fulfillmentDays": 12,
    "trustScore": 88,
    "rating": 4.7,
    "reviewCount": 35,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Ujala Mahila Mandal",
    "phone": "+91 94314 XXXXX",
    "email": "kavita.das@karigarsetu.in",
    "bio": "Pioneering contemporary Khatwa cut-work motifs blended with organic cotton textiles for boutique interiors.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-013.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Khatwa Applique Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2017-9011)",
      "Ministry of Textiles Pehchan Card (BR-PAT-APP-3319)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-013",
    "isDemoData": true
  },
  {
    "id": "artisan-014",
    "legacyId": "artisan-14",
    "code": "ART-014",
    "pehchanId": "JK-SRI-WOO-9912",
    "giRegistrationNo": "GI-AU-2016-8819",
    "name": "Manoj Das",
    "gender": "Male",
    "photo": "/images/avatars/artisan-014.svg",
    "craft": "Wood Carving",
    "category": "Wood Carving",
    "location": "Zadibal, Srinagar",
    "state": "Jammu & Kashmir",
    "district": "Srinagar",
    "cluster": "Old Srinagar Heritage Wood Carvers",
    "specialization": "Relief wood carving on seasoned Kashmiri walnut root wood with chinar leaf motifs",
    "experience": "26 Years of Master Wood Carving",
    "experienceYears": 26,
    "capacity": "30 pieces/month",
    "capacityPerMonth": 30,
    "fulfillmentDays": 15,
    "trustScore": 97,
    "rating": 5,
    "reviewCount": 140,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Kashmir Walnut Wood Workers Society",
    "phone": "+91 94190 XXXXX",
    "email": "manoj.das@karigarsetu.in",
    "bio": "Master woodworker carving seasoned root wood without any artificial chemical dyes or plastic lacquer.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-014.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Wood Carving",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2016-8819)",
      "Ministry of Textiles Pehchan Card (JK-SRI-WOO-9912)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-014",
    "isDemoData": true
  },
  {
    "id": "artisan-015",
    "legacyId": "artisan-15",
    "code": "ART-015",
    "pehchanId": "OD-CUT-TAR-9012",
    "giRegistrationNo": "GI-AU-2023-1190",
    "name": "Laxmi Pradhan",
    "gender": "Female",
    "photo": "/images/avatars/artisan-015.svg",
    "craft": "Tribal Jewellery",
    "category": "Metal Craft",
    "location": "Alisha Bazar, Cuttack",
    "state": "Odisha",
    "district": "Cuttack",
    "cluster": "Cuttack Tarkasi Artisans Guild",
    "specialization": "Delicate gossamer silver wire jewellery, vermillion boxes, and peacock brooches",
    "experience": "16 Years of Tarkasi Filigree",
    "experienceYears": 16,
    "capacity": "40 pieces/month",
    "capacityPerMonth": 40,
    "fulfillmentDays": 10,
    "trustScore": 94,
    "rating": 4.9,
    "reviewCount": 75,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Tarkasi Mahila Samiti",
    "phone": "+91 94372 XXXXX",
    "email": "laxmi.pradhan@karigarsetu.in",
    "bio": "Draws 99% fine silver into hair-thin wires to shape lightweight gossamer floral jewellery and decorative peacock centerpieces.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-015.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Tribal Jewellery",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2023-1190)",
      "Ministry of Textiles Pehchan Card (OD-CUT-TAR-9012)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-015",
    "isDemoData": true
  },
  {
    "id": "artisan-016",
    "legacyId": "artisan-16",
    "code": "ART-016",
    "pehchanId": "JK-SRI-PAP-5501",
    "giRegistrationNo": "GI-AU-2017-6621",
    "name": "Bikash Pradhan",
    "gender": "Male",
    "photo": "/images/avatars/artisan-016.svg",
    "craft": "Kashmiri Paper Mache",
    "category": "Painting & Wall Art",
    "location": "Alamgari Bazar, Srinagar",
    "state": "Jammu & Kashmir",
    "district": "Srinagar",
    "cluster": "Downtown Srinagar Sakhtsazi Artisans",
    "specialization": "Sakhtsazi molded pulp boxes with 24k gold leaf Naqashi brushwork",
    "experience": "23 Years of Naqashi Art",
    "experienceYears": 23,
    "capacity": "60 pieces/month",
    "capacityPerMonth": 60,
    "fulfillmentDays": 9,
    "trustScore": 95,
    "rating": 4.9,
    "reviewCount": 92,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Kashmir Naqashi Co-operative",
    "phone": "+91 94191 XXXXX",
    "email": "bikash.pradhan@karigarsetu.in",
    "bio": "Pioneering sustainable home accents by soaking recycled paper pulp and coating with amber varnish and natural mineral paints.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-016.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Kashmiri Paper Mache",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2017-6621)",
      "Ministry of Textiles Pehchan Card (JK-SRI-PAP-5501)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-016",
    "isDemoData": true
  },
  {
    "id": "artisan-017",
    "legacyId": "artisan-17",
    "code": "ART-017",
    "pehchanId": "RJ-SNG-BLO-8812",
    "giRegistrationNo": "GI-AU-2016-4409",
    "name": "Rina Kumari",
    "gender": "Female",
    "photo": "/images/avatars/artisan-017.svg",
    "craft": "Block Printing",
    "category": "Handloom & Textiles",
    "location": "Sanganer, Jaipur",
    "state": "Rajasthan",
    "district": "Jaipur",
    "cluster": "Sanganer Hand Block Printing Cluster",
    "specialization": "Natural indigo and madder root woodblock printing on mulmul cotton fabric",
    "experience": "15 Years of Block Printing",
    "experienceYears": 15,
    "capacity": "100 pieces/month",
    "capacityPerMonth": 100,
    "fulfillmentDays": 6,
    "trustScore": 93,
    "rating": 4.8,
    "reviewCount": 84,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Sanganeri Rangrez Mandal",
    "phone": "+91 94142 XXXXX",
    "email": "rina.kumari@karigarsetu.in",
    "bio": "Hand-presses teak wood blocks with natural plant dyes onto organic cotton stoles, sarees, and yardage with precise pattern alignment.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-017.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Block Printing",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2016-4409)",
      "Ministry of Textiles Pehchan Card (RJ-SNG-BLO-8812)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-017",
    "isDemoData": true
  },
  {
    "id": "artisan-018",
    "legacyId": "artisan-18",
    "code": "ART-018",
    "pehchanId": "AS-BAR-BAM-3301",
    "giRegistrationNo": "GI-AU-2019-7711",
    "name": "Amit Kumar",
    "gender": "Male",
    "photo": "/images/avatars/artisan-018.svg",
    "craft": "Bamboo Craft",
    "category": "Natural Fibre Craft",
    "location": "Sarthebari, Barpeta",
    "state": "Assam",
    "district": "Barpeta",
    "cluster": "Lower Assam Bamboo & Cane Cluster",
    "specialization": "Muga-treated seasoned bamboo lampshades, fruit trays, and modular screens",
    "experience": "14 Years of Bamboo Work",
    "experienceYears": 14,
    "capacity": "85 pieces/month",
    "capacityPerMonth": 85,
    "fulfillmentDays": 7,
    "trustScore": 91,
    "rating": 4.8,
    "reviewCount": 56,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Brahmaputra Bamboo Craft Co-op",
    "phone": "+91 94350 XXXXX",
    "email": "amit.kumar@karigarsetu.in",
    "bio": "Splits indigenous Bambusa tulda into paper-thin flexible strips to weave contemporary eco-lighting and table accents.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-018.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Bamboo Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2019-7711)",
      "Ministry of Textiles Pehchan Card (AS-BAR-BAM-3301)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-018",
    "isDemoData": true
  },
  {
    "id": "artisan-019",
    "legacyId": "artisan-19",
    "code": "ART-019",
    "pehchanId": "UP-VAR-BAN-1002",
    "giRegistrationNo": "GI-AU-2015-0012",
    "name": "Shanti Devi",
    "gender": "Female",
    "photo": "/images/avatars/artisan-019.svg",
    "craft": "Handloom Saree",
    "category": "Handloom & Textiles",
    "location": "Kotwa, Varanasi",
    "state": "Uttar Pradesh",
    "district": "Varanasi",
    "cluster": "Varanasi Handloom Megacluster",
    "specialization": "Kadwa zari pit-loom weaving on pure mulberry Katan silk",
    "experience": "25 Years of Silk Weaving",
    "experienceYears": 25,
    "capacity": "20 pieces/month",
    "capacityPerMonth": 20,
    "fulfillmentDays": 18,
    "trustScore": 97,
    "rating": 5,
    "reviewCount": 135,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Kashi Bunkar Sahkari Samiti",
    "phone": "+91 94500 XXXXX",
    "email": "shanti.devi@karigarsetu.in",
    "bio": "Operates traditional wooden pit looms with her family, taking up to 3 weeks to weave each heirloom bridal saree with silver-gilt zari thread.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-019.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Handloom Saree",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2015-0012)",
      "Ministry of Textiles Pehchan Card (UP-VAR-BAN-1002)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-019",
    "isDemoData": true
  },
  {
    "id": "artisan-020",
    "legacyId": "artisan-20",
    "code": "ART-020",
    "pehchanId": "MP-TIK-BEL-6612",
    "giRegistrationNo": "GI-AU-2018-4410",
    "name": "Sanjay Verma",
    "gender": "Male",
    "photo": "/images/avatars/artisan-020.svg",
    "craft": "Bell Metal",
    "category": "Metal Craft",
    "location": "Tikamgarh",
    "state": "Madhya Pradesh",
    "district": "Tikamgarh",
    "cluster": "Bundelkhand Bell Metal Center",
    "specialization": "Resonant singing bell bowls, traditional bells, and ceremonial diyas",
    "experience": "20 Years of Foundry Work",
    "experienceYears": 20,
    "capacity": "70 pieces/month",
    "capacityPerMonth": 70,
    "fulfillmentDays": 8,
    "trustScore": 93,
    "rating": 4.8,
    "reviewCount": 72,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Bundelkhand Dhatu Shilp Sangh",
    "phone": "+91 94250 XXXXX",
    "email": "sanjay.verma@karigarsetu.in",
    "bio": "Smelts 78% copper and 22% tin bronze alloy to create resonant, acoustically pure singing meditation bowls and temple bells.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-020.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Bell Metal",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2018-4410)",
      "Ministry of Textiles Pehchan Card (MP-TIK-BEL-6612)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-020",
    "isDemoData": true
  },
  {
    "id": "artisan-021",
    "legacyId": "artisan-21",
    "code": "ART-021",
    "pehchanId": "MP-CHA-SIL-9901",
    "giRegistrationNo": "GI-AU-2016-1188",
    "name": "Poonam Sahu",
    "gender": "Female",
    "photo": "/images/avatars/artisan-021.svg",
    "craft": "Handloom Saree",
    "category": "Handloom & Textiles",
    "location": "Pranpur, Chanderi",
    "state": "Madhya Pradesh",
    "district": "Ashoknagar",
    "cluster": "Chanderi Handloom Heritage Park",
    "specialization": "Sheer gossamer silk-cotton blend with gold zari booti motifs",
    "experience": "16 Years of Chanderi Weaving",
    "experienceYears": 16,
    "capacity": "30 pieces/month",
    "capacityPerMonth": 30,
    "fulfillmentDays": 14,
    "trustScore": 94,
    "rating": 4.9,
    "reviewCount": 89,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Pranpur Bunkar Mandal",
    "phone": "+91 94251 XXXXX",
    "email": "poonam.sahu@karigarsetu.in",
    "bio": "Weaves lightweight, translucent Chanderi sarees with shimmering gold borders on throw-shuttle pit looms.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-021.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Handloom Saree",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2016-1188)",
      "Ministry of Textiles Pehchan Card (MP-CHA-SIL-9901)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-021",
    "isDemoData": true
  },
  {
    "id": "artisan-022",
    "legacyId": "artisan-22",
    "code": "ART-022",
    "pehchanId": "CG-JAG-DHO-7711",
    "giRegistrationNo": "GI-AU-2018-3392",
    "name": "Dhaniram Kashyap",
    "gender": "Male",
    "photo": "/images/avatars/artisan-022.svg",
    "craft": "Dhokra Jewellery",
    "category": "Tribal Jewellery",
    "location": "Jagdalpur, Bastar",
    "state": "Chhattisgarh",
    "district": "Bastar",
    "cluster": "Bastar Tribal Artisan Federation",
    "specialization": "Beeswax-wire tribal neckpieces, coin chokers, and cuff bangles",
    "experience": "18 Years of Lost-Wax Casting",
    "experienceYears": 18,
    "capacity": "55 pieces/month",
    "capacityPerMonth": 55,
    "fulfillmentDays": 9,
    "trustScore": 92,
    "rating": 4.8,
    "reviewCount": 65,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Bastar Dhokra Society",
    "phone": "+91 97524 XXXXX",
    "email": "dhaniram.kashyap@karigarsetu.in",
    "bio": "Crafts contemporary ethical brass jewellery inspired by ancient tribal body ornamentation of Bastar forests.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-022.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Dhokra Jewellery",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2018-3392)",
      "Ministry of Textiles Pehchan Card (CG-JAG-DHO-7711)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-022",
    "isDemoData": true
  },
  {
    "id": "artisan-023",
    "legacyId": "artisan-23",
    "code": "ART-023",
    "pehchanId": "GJ-KUT-ROG-1122",
    "giRegistrationNo": "GI-AU-2017-9912",
    "name": "Champa Ben",
    "gender": "Female",
    "photo": "/images/avatars/artisan-023.svg",
    "craft": "Embroidery",
    "category": "Handloom & Textiles",
    "location": "Nirona, Bhuj",
    "state": "Gujarat",
    "district": "Kutch",
    "cluster": "Kutch Desert Craft Guild",
    "specialization": "Boiled castor oil castor gel paint with iron stylus and Ahir embroidery",
    "experience": "22 Years of Rogan Art",
    "experienceYears": 22,
    "capacity": "25 pieces/month",
    "capacityPerMonth": 25,
    "fulfillmentDays": 16,
    "trustScore": 96,
    "rating": 5,
    "reviewCount": 115,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Nirona Women Craft Group",
    "phone": "+91 98250 XXXXX",
    "email": "champa.ben@karigarsetu.in",
    "bio": "Preserves the 300-year-old Persian Rogan painting method of creating vibrant floral motifs on handloom khadi with castor paste.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-023.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Embroidery",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2017-9912)",
      "Ministry of Textiles Pehchan Card (GJ-KUT-ROG-1122)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-023",
    "isDemoData": true
  },
  {
    "id": "artisan-024",
    "legacyId": "artisan-24",
    "code": "ART-024",
    "pehchanId": "HP-KUL-SHA-4402",
    "giRegistrationNo": "GI-AU-2016-0044",
    "name": "Prem Chand",
    "gender": "Male",
    "photo": "/images/avatars/artisan-024.svg",
    "craft": "Handwoven Stoles",
    "category": "Handloom & Textiles",
    "location": "Naggar, Kullu",
    "state": "Himachal Pradesh",
    "district": "Kullu",
    "cluster": "Kullu Valley Wool Weavers Co-operative",
    "specialization": "Merino and Angora wool shawls with geometrical dovetail tapestry borders",
    "experience": "20 Years of Wool Weaving",
    "experienceYears": 20,
    "capacity": "40 pieces/month",
    "capacityPerMonth": 40,
    "fulfillmentDays": 11,
    "trustScore": 94,
    "rating": 4.9,
    "reviewCount": 98,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Himachal Woolcraft Federation",
    "phone": "+91 94180 XXXXX",
    "email": "prem.chand@karigarsetu.in",
    "bio": "Spins and weaves certified pure Himalayan merino wool with traditional diamond pattern borders using wooden frame fly-shuttle looms.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-024.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Handwoven Stoles",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2016-0044)",
      "Ministry of Textiles Pehchan Card (HP-KUL-SHA-4402)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-024",
    "isDemoData": true
  },
  {
    "id": "artisan-025",
    "legacyId": "artisan-25",
    "code": "ART-025",
    "pehchanId": "UK-ALM-AIP-8821",
    "giRegistrationNo": "GI-AU-2021-3310",
    "name": "Sunita Negi",
    "gender": "Female",
    "photo": "/images/avatars/artisan-025.svg",
    "craft": "Painting & Wall Art",
    "category": "Painting & Wall Art",
    "location": "Almora",
    "state": "Uttarakhand",
    "district": "Almora",
    "cluster": "Kumaon Aipan Shilp Sansthan",
    "specialization": "Geru red mud base with soaked rice flour paste (Biswar) linear floor art",
    "experience": "12 Years of Aipan",
    "experienceYears": 12,
    "capacity": "50 pieces/month",
    "capacityPerMonth": 50,
    "fulfillmentDays": 8,
    "trustScore": 91,
    "rating": 4.8,
    "reviewCount": 48,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Kumaoni Mahila Kala Manch",
    "phone": "+91 94111 XXXXX",
    "email": "sunita.negi@karigarsetu.in",
    "bio": "Transforms ancient ritualistic Kumaon floor motifs onto wooden chowkis, terracotta plates, and decorative interior panels.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-025.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Painting & Wall Art",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2021-3310)",
      "Ministry of Textiles Pehchan Card (UK-ALM-AIP-8821)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-025",
    "isDemoData": true
  },
  {
    "id": "artisan-026",
    "legacyId": "artisan-26",
    "code": "ART-026",
    "pehchanId": "UP-MRD-ENG-9921",
    "giRegistrationNo": "GI-AU-2016-1044",
    "name": "Vijay Kumar Rastogi",
    "gender": "Male",
    "photo": "/images/avatars/artisan-026.svg",
    "craft": "Brass Craft",
    "category": "Metal Craft",
    "location": "Moradabad",
    "state": "Uttar Pradesh",
    "district": "Moradabad",
    "cluster": "Moradabad Brass City Cluster",
    "specialization": "Deep champlevé engraving and antique nickel patina on brass planters and vases",
    "experience": "25 Years of Metal Engraving",
    "experienceYears": 25,
    "capacity": "250 pieces/month",
    "capacityPerMonth": 250,
    "fulfillmentDays": 6,
    "trustScore": 96,
    "rating": 5,
    "reviewCount": 150,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Moradabad Brass Exporters Guild",
    "phone": "+91 94122 XXXXX",
    "email": "vijay.rastogi@karigarsetu.in",
    "bio": "Operates an ISO-compliant high-volume brass engraving workshop capable of catering to large corporate Diwali gifting and export orders.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-026.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Brass Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2016-1044)",
      "Ministry of Textiles Pehchan Card (UP-MRD-ENG-9921)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-026",
    "isDemoData": true
  },
  {
    "id": "artisan-027",
    "legacyId": "artisan-27",
    "code": "ART-027",
    "pehchanId": "TA-THA-TAN-1027",
    "giRegistrationNo": "GI-AU-2018-2027",
    "name": "Padmawati Amma",
    "gender": "Female",
    "photo": "/images/avatars/artisan-027.svg",
    "craft": "Tanjore Gold Painting",
    "category": "Painting & Wall Art",
    "location": "Thanjavur",
    "state": "Tamil Nadu",
    "district": "Thanjavur",
    "cluster": "Thanjavur Craft Cluster",
    "specialization": "Authentic Tanjore Gold Painting heritage art",
    "experience": "28 Years of Traditional Art",
    "experienceYears": 28,
    "capacity": "20 pieces/month",
    "capacityPerMonth": 20,
    "fulfillmentDays": 14,
    "trustScore": 95,
    "rating": 4.8,
    "reviewCount": 84,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Thanjavur Karigar Samiti",
    "phone": "+91 94127 XXXXX",
    "email": "padmawati.amma@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 28 years preserving authentic Indian Tanjore Gold Painting traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-027.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Tanjore Gold Painting",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2018-2027)",
      "Ministry of Textiles Pehchan Card (TA-THA-TAN-1027)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-027",
    "isDemoData": true
  },
  {
    "id": "artisan-028",
    "legacyId": "artisan-28",
    "code": "ART-028",
    "pehchanId": "AN-KAL-KAL-1028",
    "giRegistrationNo": "GI-AU-2019-2028",
    "name": "Nirmala Devi",
    "gender": "Female",
    "photo": "/images/avatars/artisan-028.svg",
    "craft": "Kalamkari Painting",
    "category": "Painting & Wall Art",
    "location": "Kalamkari Town, Machilipatnam",
    "state": "Andhra Pradesh",
    "district": "Kalamkari Town",
    "cluster": "Kalamkari Town, Machilipatnam Craft Cluster",
    "specialization": "Authentic Kalamkari Painting heritage art",
    "experience": "17 Years of Traditional Art",
    "experienceYears": 17,
    "capacity": "45 pieces/month",
    "capacityPerMonth": 45,
    "fulfillmentDays": 8,
    "trustScore": 96,
    "rating": 4.8,
    "reviewCount": 86,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Kalamkari Town, Machilipatnam Karigar Samiti",
    "phone": "+91 94128 XXXXX",
    "email": "nirmala.devi@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 17 years preserving authentic Indian Kalamkari Painting traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-028.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Kalamkari Painting",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2019-2028)",
      "Ministry of Textiles Pehchan Card (AN-KAL-KAL-1028)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-028",
    "isDemoData": true
  },
  {
    "id": "artisan-029",
    "legacyId": "artisan-29",
    "code": "ART-029",
    "pehchanId": "MA-DAH-WAR-1029",
    "giRegistrationNo": "GI-AU-2020-2029",
    "name": "Radha Bai",
    "gender": "Female",
    "photo": "/images/avatars/artisan-029.svg",
    "craft": "Warli Painting",
    "category": "Painting & Wall Art",
    "location": "Dahanu, Palghar",
    "state": "Maharashtra",
    "district": "Dahanu",
    "cluster": "Dahanu, Palghar Craft Cluster",
    "specialization": "Authentic Warli Painting heritage art",
    "experience": "14 Years of Traditional Art",
    "experienceYears": 14,
    "capacity": "60 pieces/month",
    "capacityPerMonth": 60,
    "fulfillmentDays": 9,
    "trustScore": 97,
    "rating": 4.8,
    "reviewCount": 88,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Dahanu, Palghar Karigar Samiti",
    "phone": "+91 94129 XXXXX",
    "email": "radha.bai@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 14 years preserving authentic Indian Warli Painting traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-029.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Warli Painting",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2020-2029)",
      "Ministry of Textiles Pehchan Card (MA-DAH-WAR-1029)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-029",
    "isDemoData": true
  },
  {
    "id": "artisan-030",
    "legacyId": "artisan-30",
    "code": "ART-030",
    "pehchanId": "PU-HOS-PHU-1030",
    "giRegistrationNo": "GI-AU-2021-2030",
    "name": "Lata Devi",
    "gender": "Female",
    "photo": "/images/avatars/artisan-030.svg",
    "craft": "Phulkari Embroidery",
    "category": "Handloom & Textiles",
    "location": "Hoshiarpur",
    "state": "Punjab",
    "district": "Hoshiarpur",
    "cluster": "Hoshiarpur Craft Cluster",
    "specialization": "Authentic Phulkari Embroidery heritage art",
    "experience": "19 Years of Traditional Art",
    "experienceYears": 19,
    "capacity": "35 pieces/month",
    "capacityPerMonth": 35,
    "fulfillmentDays": 10,
    "trustScore": 88,
    "rating": 4.8,
    "reviewCount": 90,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Hoshiarpur Karigar Samiti",
    "phone": "+91 94130 XXXXX",
    "email": "lata.devi@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 19 years preserving authentic Indian Phulkari Embroidery traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-030.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Phulkari Embroidery",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2021-2030)",
      "Ministry of Textiles Pehchan Card (PU-HOS-PHU-1030)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-030",
    "isDemoData": true
  },
  {
    "id": "artisan-031",
    "legacyId": "artisan-31",
    "code": "ART-031",
    "pehchanId": "TR-AGA-CAN-1031",
    "giRegistrationNo": "GI-AU-2022-2031",
    "name": "Sumitra Roy",
    "gender": "Female",
    "photo": "/images/avatars/artisan-031.svg",
    "craft": "Cane Craft",
    "category": "Home & Living",
    "location": "Agartala",
    "state": "Tripura",
    "district": "Agartala",
    "cluster": "Agartala Craft Cluster",
    "specialization": "Authentic Cane Craft heritage art",
    "experience": "12 Years of Traditional Art",
    "experienceYears": 12,
    "capacity": "70 pieces/month",
    "capacityPerMonth": 70,
    "fulfillmentDays": 11,
    "trustScore": 89,
    "rating": 4.8,
    "reviewCount": 92,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Agartala Karigar Samiti",
    "phone": "+91 94131 XXXXX",
    "email": "sumitra.roy@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 12 years preserving authentic Indian Cane Craft traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-031.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Cane Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2022-2031)",
      "Ministry of Textiles Pehchan Card (TR-AGA-CAN-1031)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-031",
    "isDemoData": true
  },
  {
    "id": "artisan-032",
    "legacyId": "artisan-32",
    "code": "ART-032",
    "pehchanId": "KE-ARA-BEL-1032",
    "giRegistrationNo": "GI-AU-2015-2032",
    "name": "Kamala Das",
    "gender": "Female",
    "photo": "/images/avatars/artisan-032.svg",
    "craft": "Bell Metal",
    "category": "Metal Craft",
    "location": "Aranmula",
    "state": "Kerala",
    "district": "Aranmula",
    "cluster": "Aranmula Craft Cluster",
    "specialization": "Authentic Bell Metal heritage art",
    "experience": "21 Years of Traditional Art",
    "experienceYears": 21,
    "capacity": "25 pieces/month",
    "capacityPerMonth": 25,
    "fulfillmentDays": 12,
    "trustScore": 90,
    "rating": 4.8,
    "reviewCount": 94,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Aranmula Karigar Samiti",
    "phone": "+91 94132 XXXXX",
    "email": "kamala.das@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 21 years preserving authentic Indian Bell Metal traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-032.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Bell Metal",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2015-2032)",
      "Ministry of Textiles Pehchan Card (KE-ARA-BEL-1032)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-032",
    "isDemoData": true
  },
  {
    "id": "artisan-033",
    "legacyId": "artisan-33",
    "code": "ART-033",
    "pehchanId": "RA-PRA-THE-1033",
    "giRegistrationNo": "GI-AU-2016-2033",
    "name": "Urmila Soni",
    "gender": "Female",
    "photo": "/images/avatars/artisan-033.svg",
    "craft": "Thewa Gold Jewelry",
    "category": "Home & Living",
    "location": "Pratapgarh",
    "state": "Rajasthan",
    "district": "Pratapgarh",
    "cluster": "Pratapgarh Craft Cluster",
    "specialization": "Authentic Thewa Gold Jewelry heritage art",
    "experience": "15 Years of Traditional Art",
    "experienceYears": 15,
    "capacity": "30 pieces/month",
    "capacityPerMonth": 30,
    "fulfillmentDays": 13,
    "trustScore": 91,
    "rating": 4.8,
    "reviewCount": 96,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Pratapgarh Karigar Samiti",
    "phone": "+91 94133 XXXXX",
    "email": "urmila.soni@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 15 years preserving authentic Indian Thewa Gold Jewelry traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-033.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Thewa Gold Jewelry",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2016-2033)",
      "Ministry of Textiles Pehchan Card (RA-PRA-THE-1033)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-033",
    "isDemoData": true
  },
  {
    "id": "artisan-034",
    "legacyId": "artisan-34",
    "code": "ART-034",
    "pehchanId": "JH-DUM-JUT-1034",
    "giRegistrationNo": "GI-AU-2017-2034",
    "name": "Bimala Soren",
    "gender": "Female",
    "photo": "/images/avatars/artisan-034.svg",
    "craft": "Jute Craft",
    "category": "Home & Living",
    "location": "Dumka",
    "state": "Jharkhand",
    "district": "Dumka",
    "cluster": "Dumka Craft Cluster",
    "specialization": "Authentic Jute Craft heritage art",
    "experience": "11 Years of Traditional Art",
    "experienceYears": 11,
    "capacity": "80 pieces/month",
    "capacityPerMonth": 80,
    "fulfillmentDays": 14,
    "trustScore": 92,
    "rating": 4.8,
    "reviewCount": 98,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Dumka Karigar Samiti",
    "phone": "+91 94134 XXXXX",
    "email": "bimala.soren@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 11 years preserving authentic Indian Jute Craft traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-034.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Jute Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2017-2034)",
      "Ministry of Textiles Pehchan Card (JH-DUM-JUT-1034)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-034",
    "isDemoData": true
  },
  {
    "id": "artisan-035",
    "legacyId": "artisan-35",
    "code": "ART-035",
    "pehchanId": "TE-POC-HAN-1035",
    "giRegistrationNo": "GI-AU-2018-2035",
    "name": "Shalini Reddy",
    "gender": "Female",
    "photo": "/images/avatars/artisan-035.svg",
    "craft": "Handloom Saree",
    "category": "Home & Living",
    "location": "Pochampally",
    "state": "Telangana",
    "district": "Pochampally",
    "cluster": "Pochampally Craft Cluster",
    "specialization": "Authentic Handloom Saree heritage art",
    "experience": "18 Years of Traditional Art",
    "experienceYears": 18,
    "capacity": "40 pieces/month",
    "capacityPerMonth": 40,
    "fulfillmentDays": 8,
    "trustScore": 93,
    "rating": 4.8,
    "reviewCount": 100,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Pochampally Karigar Samiti",
    "phone": "+91 94135 XXXXX",
    "email": "shalini.reddy@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 18 years preserving authentic Indian Handloom Saree traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-035.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Handloom Saree",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2018-2035)",
      "Ministry of Textiles Pehchan Card (TE-POC-HAN-1035)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-035",
    "isDemoData": true
  },
  {
    "id": "artisan-036",
    "legacyId": "artisan-36",
    "code": "ART-036",
    "pehchanId": "GO-BIC-CER-1036",
    "giRegistrationNo": "GI-AU-2019-2036",
    "name": "Devika Rani",
    "gender": "Female",
    "photo": "/images/avatars/artisan-036.svg",
    "craft": "Ceramic Craft",
    "category": "Home & Living",
    "location": "Bicholim",
    "state": "Goa",
    "district": "Bicholim",
    "cluster": "Bicholim Craft Cluster",
    "specialization": "Authentic Ceramic Craft heritage art",
    "experience": "10 Years of Traditional Art",
    "experienceYears": 10,
    "capacity": "65 pieces/month",
    "capacityPerMonth": 65,
    "fulfillmentDays": 9,
    "trustScore": 94,
    "rating": 4.8,
    "reviewCount": 102,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Bicholim Karigar Samiti",
    "phone": "+91 94136 XXXXX",
    "email": "devika.rani@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 10 years preserving authentic Indian Ceramic Craft traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-036.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Ceramic Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2019-2036)",
      "Ministry of Textiles Pehchan Card (GO-BIC-CER-1036)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-036",
    "isDemoData": true
  },
  {
    "id": "artisan-037",
    "legacyId": "artisan-37",
    "code": "ART-037",
    "pehchanId": "CH-RAI-KOS-1037",
    "giRegistrationNo": "GI-AU-2020-2037",
    "name": "Hema Malini Sahu",
    "gender": "Female",
    "photo": "/images/avatars/artisan-037.svg",
    "craft": "Kosa Silk Weaving",
    "category": "Handloom & Textiles",
    "location": "Raigarh",
    "state": "Chhattisgarh",
    "district": "Raigarh",
    "cluster": "Raigarh Craft Cluster",
    "specialization": "Authentic Kosa Silk Weaving heritage art",
    "experience": "16 Years of Traditional Art",
    "experienceYears": 16,
    "capacity": "30 pieces/month",
    "capacityPerMonth": 30,
    "fulfillmentDays": 10,
    "trustScore": 95,
    "rating": 4.8,
    "reviewCount": 104,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Raigarh Karigar Samiti",
    "phone": "+91 94137 XXXXX",
    "email": "hema.malini.sahu@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 16 years preserving authentic Indian Kosa Silk Weaving traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-037.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Kosa Silk Weaving",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2020-2037)",
      "Ministry of Textiles Pehchan Card (CH-RAI-KOS-1037)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-037",
    "isDemoData": true
  },
  {
    "id": "artisan-038",
    "legacyId": "artisan-38",
    "code": "ART-038",
    "pehchanId": "MA-BAG-BLO-1038",
    "giRegistrationNo": "GI-AU-2021-2038",
    "name": "Pushpa Bai",
    "gender": "Female",
    "photo": "/images/avatars/artisan-038.svg",
    "craft": "Block Printing",
    "category": "Home & Living",
    "location": "Bagh",
    "state": "Madhya Pradesh",
    "district": "Bagh",
    "cluster": "Bagh Craft Cluster",
    "specialization": "Authentic Block Printing heritage art",
    "experience": "22 Years of Traditional Art",
    "experienceYears": 22,
    "capacity": "90 pieces/month",
    "capacityPerMonth": 90,
    "fulfillmentDays": 11,
    "trustScore": 96,
    "rating": 4.8,
    "reviewCount": 106,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Bagh Karigar Samiti",
    "phone": "+91 94138 XXXXX",
    "email": "pushpa.bai@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 22 years preserving authentic Indian Block Printing traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-038.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Block Printing",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2021-2038)",
      "Ministry of Textiles Pehchan Card (MA-BAG-BLO-1038)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-038",
    "isDemoData": true
  },
  {
    "id": "artisan-039",
    "legacyId": "artisan-39",
    "code": "ART-039",
    "pehchanId": "GU-PAT-PAT-1039",
    "giRegistrationNo": "GI-AU-2022-2039",
    "name": "Geeta Ben",
    "gender": "Female",
    "photo": "/images/avatars/artisan-039.svg",
    "craft": "Patan Patola",
    "category": "Home & Living",
    "location": "Patan",
    "state": "Gujarat",
    "district": "Patan",
    "cluster": "Patan Craft Cluster",
    "specialization": "Authentic Patan Patola heritage art",
    "experience": "30 Years of Traditional Art",
    "experienceYears": 30,
    "capacity": "15 pieces/month",
    "capacityPerMonth": 15,
    "fulfillmentDays": 12,
    "trustScore": 97,
    "rating": 4.8,
    "reviewCount": 108,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Patan Karigar Samiti",
    "phone": "+91 94139 XXXXX",
    "email": "geeta.ben@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 30 years preserving authentic Indian Patan Patola traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-039.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Patan Patola",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2022-2039)",
      "Ministry of Textiles Pehchan Card (GU-PAT-PAT-1039)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-039",
    "isDemoData": true
  },
  {
    "id": "artisan-040",
    "legacyId": "artisan-40",
    "code": "ART-040",
    "pehchanId": "KE-ARA-MET-1040",
    "giRegistrationNo": "GI-AU-2015-2040",
    "name": "Gopal Krishna",
    "gender": "Male",
    "photo": "/images/avatars/artisan-040.svg",
    "craft": "Metal Craft",
    "category": "Metal Craft",
    "location": "Aranmula",
    "state": "Kerala",
    "district": "Aranmula",
    "cluster": "Aranmula Craft Cluster",
    "specialization": "Authentic Metal Craft heritage art",
    "experience": "27 Years of Traditional Art",
    "experienceYears": 27,
    "capacity": "20 pieces/month",
    "capacityPerMonth": 20,
    "fulfillmentDays": 13,
    "trustScore": 88,
    "rating": 4.8,
    "reviewCount": 110,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Aranmula Karigar Samiti",
    "phone": "+91 94140 XXXXX",
    "email": "gopal.krishna@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 27 years preserving authentic Indian Metal Craft traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-040.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Metal Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2015-2040)",
      "Ministry of Textiles Pehchan Card (KE-ARA-MET-1040)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-040",
    "isDemoData": true
  },
  {
    "id": "artisan-041",
    "legacyId": "artisan-41",
    "code": "ART-041",
    "pehchanId": "RA-MOU-LEA-1041",
    "giRegistrationNo": "GI-AU-2016-2041",
    "name": "Brij Mohan",
    "gender": "Male",
    "photo": "/images/avatars/artisan-041.svg",
    "craft": "Leather Craft",
    "category": "Home & Living",
    "location": "Moulana, Udaipur",
    "state": "Rajasthan",
    "district": "Moulana",
    "cluster": "Moulana, Udaipur Craft Cluster",
    "specialization": "Authentic Leather Craft heritage art",
    "experience": "16 Years of Traditional Art",
    "experienceYears": 16,
    "capacity": "80 pieces/month",
    "capacityPerMonth": 80,
    "fulfillmentDays": 14,
    "trustScore": 89,
    "rating": 4.8,
    "reviewCount": 112,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Moulana, Udaipur Karigar Samiti",
    "phone": "+91 94141 XXXXX",
    "email": "brij.mohan@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 16 years preserving authentic Indian Leather Craft traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-041.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Leather Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2016-2041)",
      "Ministry of Textiles Pehchan Card (RA-MOU-LEA-1041)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-041",
    "isDemoData": true
  },
  {
    "id": "artisan-042",
    "legacyId": "artisan-42",
    "code": "ART-042",
    "pehchanId": "LA-LEH-THA-1042",
    "giRegistrationNo": "GI-AU-2017-2042",
    "name": "Tsering Dorje",
    "gender": "Male",
    "photo": "/images/avatars/artisan-042.svg",
    "craft": "Thangka Painting",
    "category": "Painting & Wall Art",
    "location": "Leh",
    "state": "Ladakh",
    "district": "Leh",
    "cluster": "Leh Craft Cluster",
    "specialization": "Authentic Thangka Painting heritage art",
    "experience": "25 Years of Traditional Art",
    "experienceYears": 25,
    "capacity": "15 pieces/month",
    "capacityPerMonth": 15,
    "fulfillmentDays": 8,
    "trustScore": 90,
    "rating": 4.8,
    "reviewCount": 114,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Leh Karigar Samiti",
    "phone": "+91 94142 XXXXX",
    "email": "tsering.dorje@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 25 years preserving authentic Indian Thangka Painting traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-042.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Thangka Painting",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2017-2042)",
      "Ministry of Textiles Pehchan Card (LA-LEH-THA-1042)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-042",
    "isDemoData": true
  },
  {
    "id": "artisan-043",
    "legacyId": "artisan-43",
    "code": "ART-043",
    "pehchanId": "JA-SRI-PAS-1043",
    "giRegistrationNo": "GI-AU-2018-2043",
    "name": "Abdul Ghani",
    "gender": "Male",
    "photo": "/images/avatars/artisan-043.svg",
    "craft": "Pashmina Shawl",
    "category": "Handloom & Textiles",
    "location": "Srinagar",
    "state": "Jammu & Kashmir",
    "district": "Srinagar",
    "cluster": "Srinagar Craft Cluster",
    "specialization": "Authentic Pashmina Shawl heritage art",
    "experience": "32 Years of Traditional Art",
    "experienceYears": 32,
    "capacity": "20 pieces/month",
    "capacityPerMonth": 20,
    "fulfillmentDays": 9,
    "trustScore": 91,
    "rating": 4.8,
    "reviewCount": 116,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Srinagar Karigar Samiti",
    "phone": "+91 94143 XXXXX",
    "email": "abdul.ghani@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 32 years preserving authentic Indian Pashmina Shawl traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-043.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Pashmina Shawl",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2018-2043)",
      "Ministry of Textiles Pehchan Card (JA-SRI-PAS-1043)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-043",
    "isDemoData": true
  },
  {
    "id": "artisan-044",
    "legacyId": "artisan-44",
    "code": "ART-044",
    "pehchanId": "AN-KON-HAN-1044",
    "giRegistrationNo": "GI-AU-2019-2044",
    "name": "Naveen Babu",
    "gender": "Male",
    "photo": "/images/avatars/artisan-044.svg",
    "craft": "Handmade Toys",
    "category": "Home & Living",
    "location": "Kondapalli",
    "state": "Andhra Pradesh",
    "district": "Kondapalli",
    "cluster": "Kondapalli Craft Cluster",
    "specialization": "Authentic Handmade Toys heritage art",
    "experience": "15 Years of Traditional Art",
    "experienceYears": 15,
    "capacity": "100 pieces/month",
    "capacityPerMonth": 100,
    "fulfillmentDays": 10,
    "trustScore": 92,
    "rating": 4.8,
    "reviewCount": 118,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Kondapalli Karigar Samiti",
    "phone": "+91 94144 XXXXX",
    "email": "naveen.babu@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 15 years preserving authentic Indian Handmade Toys traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-044.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Handmade Toys",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2019-2044)",
      "Ministry of Textiles Pehchan Card (AN-KON-HAN-1044)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-044",
    "isDemoData": true
  },
  {
    "id": "artisan-045",
    "legacyId": "artisan-45",
    "code": "ART-045",
    "pehchanId": "TA-SWA-BRO-1045",
    "giRegistrationNo": "GI-AU-2020-2045",
    "name": "Krishnamurthy",
    "gender": "Male",
    "photo": "/images/avatars/artisan-045.svg",
    "craft": "Bronze Casting",
    "category": "Home & Living",
    "location": "Swamimalai",
    "state": "Tamil Nadu",
    "district": "Swamimalai",
    "cluster": "Swamimalai Craft Cluster",
    "specialization": "Authentic Bronze Casting heritage art",
    "experience": "26 Years of Traditional Art",
    "experienceYears": 26,
    "capacity": "25 pieces/month",
    "capacityPerMonth": 25,
    "fulfillmentDays": 11,
    "trustScore": 93,
    "rating": 4.8,
    "reviewCount": 120,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Swamimalai Karigar Samiti",
    "phone": "+91 94145 XXXXX",
    "email": "krishnamurthy@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 26 years preserving authentic Indian Bronze Casting traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-045.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Bronze Casting",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2020-2045)",
      "Ministry of Textiles Pehchan Card (TA-SWA-BRO-1045)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-045",
    "isDemoData": true
  },
  {
    "id": "artisan-046",
    "legacyId": "artisan-46",
    "code": "ART-046",
    "pehchanId": "PU-AMR-BRA-1046",
    "giRegistrationNo": "GI-AU-2021-2046",
    "name": "Baldev Singh",
    "gender": "Male",
    "photo": "/images/avatars/artisan-046.svg",
    "craft": "Brass Craft",
    "category": "Metal Craft",
    "location": "Amritsar",
    "state": "Punjab",
    "district": "Amritsar",
    "cluster": "Amritsar Craft Cluster",
    "specialization": "Authentic Brass Craft heritage art",
    "experience": "18 Years of Traditional Art",
    "experienceYears": 18,
    "capacity": "60 pieces/month",
    "capacityPerMonth": 60,
    "fulfillmentDays": 12,
    "trustScore": 94,
    "rating": 4.8,
    "reviewCount": 122,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Amritsar Karigar Samiti",
    "phone": "+91 94146 XXXXX",
    "email": "baldev.singh@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 18 years preserving authentic Indian Brass Craft traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-046.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Brass Craft",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2021-2046)",
      "Ministry of Textiles Pehchan Card (PU-AMR-BRA-1046)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-046",
    "isDemoData": true
  },
  {
    "id": "artisan-047",
    "legacyId": "artisan-47",
    "code": "ART-047",
    "pehchanId": "AS-MAJ-HAN-1047",
    "giRegistrationNo": "GI-AU-2022-2047",
    "name": "Manabendra Nath",
    "gender": "Male",
    "photo": "/images/avatars/artisan-047.svg",
    "craft": "Handmade Masks",
    "category": "Home & Living",
    "location": "Majuli",
    "state": "Assam",
    "district": "Majuli",
    "cluster": "Majuli Craft Cluster",
    "specialization": "Authentic Handmade Masks heritage art",
    "experience": "20 Years of Traditional Art",
    "experienceYears": 20,
    "capacity": "40 pieces/month",
    "capacityPerMonth": 40,
    "fulfillmentDays": 13,
    "trustScore": 95,
    "rating": 4.8,
    "reviewCount": 124,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Majuli Karigar Samiti",
    "phone": "+91 94147 XXXXX",
    "email": "manabendra.nath@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 20 years preserving authentic Indian Handmade Masks traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-047.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Handmade Masks",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2022-2047)",
      "Ministry of Textiles Pehchan Card (AS-MAJ-HAN-1047)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-047",
    "isDemoData": true
  },
  {
    "id": "artisan-048",
    "legacyId": "artisan-48",
    "code": "ART-048",
    "pehchanId": "KA-BID-BID-1048",
    "giRegistrationNo": "GI-AU-2015-2048",
    "name": "Chenna Keshav",
    "gender": "Male",
    "photo": "/images/avatars/artisan-048.svg",
    "craft": "Bidriware",
    "category": "Home & Living",
    "location": "Bidar",
    "state": "Karnataka",
    "district": "Bidar",
    "cluster": "Bidar Craft Cluster",
    "specialization": "Authentic Bidriware heritage art",
    "experience": "22 Years of Traditional Art",
    "experienceYears": 22,
    "capacity": "50 pieces/month",
    "capacityPerMonth": 50,
    "fulfillmentDays": 14,
    "trustScore": 96,
    "rating": 4.8,
    "reviewCount": 126,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Bidar Karigar Samiti",
    "phone": "+91 94148 XXXXX",
    "email": "chenna.keshav@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 22 years preserving authentic Indian Bidriware traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-048.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Bidriware",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2015-2048)",
      "Ministry of Textiles Pehchan Card (KA-BID-BID-1048)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-048",
    "isDemoData": true
  },
  {
    "id": "artisan-049",
    "legacyId": "artisan-49",
    "code": "ART-049",
    "pehchanId": "RA-POK-TER-1049",
    "giRegistrationNo": "GI-AU-2016-2049",
    "name": "Ratan Lal",
    "gender": "Male",
    "photo": "/images/avatars/artisan-049.svg",
    "craft": "Terracotta",
    "category": "Home & Living",
    "location": "Pokhran",
    "state": "Rajasthan",
    "district": "Pokhran",
    "cluster": "Pokhran Craft Cluster",
    "specialization": "Authentic Terracotta heritage art",
    "experience": "17 Years of Traditional Art",
    "experienceYears": 17,
    "capacity": "85 pieces/month",
    "capacityPerMonth": 85,
    "fulfillmentDays": 8,
    "trustScore": 97,
    "rating": 4.8,
    "reviewCount": 128,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Pokhran Karigar Samiti",
    "phone": "+91 94149 XXXXX",
    "email": "ratan.lal@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 17 years preserving authentic Indian Terracotta traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-049.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Terracotta",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2016-2049)",
      "Ministry of Textiles Pehchan Card (RA-POK-TER-1049)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-049",
    "isDemoData": true
  },
  {
    "id": "artisan-050",
    "legacyId": "artisan-50",
    "code": "ART-050",
    "pehchanId": "UT-VAR-WOO-1050",
    "giRegistrationNo": "GI-AU-2017-2050",
    "name": "Harishankar",
    "gender": "Male",
    "photo": "/images/avatars/artisan-050.svg",
    "craft": "Wooden Lacquer Toys",
    "category": "Home & Living",
    "location": "Varanasi",
    "state": "Uttar Pradesh",
    "district": "Varanasi",
    "cluster": "Varanasi Craft Cluster",
    "specialization": "Authentic Wooden Lacquer Toys heritage art",
    "experience": "19 Years of Traditional Art",
    "experienceYears": 19,
    "capacity": "90 pieces/month",
    "capacityPerMonth": 90,
    "fulfillmentDays": 9,
    "trustScore": 88,
    "rating": 4.8,
    "reviewCount": 130,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Varanasi Karigar Samiti",
    "phone": "+91 94150 XXXXX",
    "email": "harishankar@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 19 years preserving authentic Indian Wooden Lacquer Toys traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-050.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Wooden Lacquer Toys",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2017-2050)",
      "Ministry of Textiles Pehchan Card (UT-VAR-WOO-1050)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-050",
    "isDemoData": true
  },
  {
    "id": "artisan-051",
    "legacyId": "artisan-51",
    "code": "ART-051",
    "pehchanId": "HI-DHA-WOO-1051",
    "giRegistrationNo": "GI-AU-2018-2051",
    "name": "Tenzin Norbu",
    "gender": "Male",
    "photo": "/images/avatars/artisan-051.svg",
    "craft": "Wood Carving",
    "category": "Home & Living",
    "location": "Dharamshala",
    "state": "Himachal Pradesh",
    "district": "Dharamshala",
    "cluster": "Dharamshala Craft Cluster",
    "specialization": "Authentic Wood Carving heritage art",
    "experience": "24 Years of Traditional Art",
    "experienceYears": 24,
    "capacity": "30 pieces/month",
    "capacityPerMonth": 30,
    "fulfillmentDays": 10,
    "trustScore": 89,
    "rating": 4.8,
    "reviewCount": 132,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Dharamshala Karigar Samiti",
    "phone": "+91 94151 XXXXX",
    "email": "tenzin.norbu@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 24 years preserving authentic Indian Wood Carving traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-051.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Wood Carving",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2018-2051)",
      "Ministry of Textiles Pehchan Card (HI-DHA-WOO-1051)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-051",
    "isDemoData": true
  },
  {
    "id": "artisan-052",
    "legacyId": "artisan-52",
    "code": "ART-052",
    "pehchanId": "TE-NIR-PAI-1052",
    "giRegistrationNo": "GI-AU-2019-2052",
    "name": "Prakash Rao",
    "gender": "Male",
    "photo": "/images/avatars/artisan-052.svg",
    "craft": "Painting & Wall Art",
    "category": "Painting & Wall Art",
    "location": "Nirmal",
    "state": "Telangana",
    "district": "Nirmal",
    "cluster": "Nirmal Craft Cluster",
    "specialization": "Authentic Painting & Wall Art heritage art",
    "experience": "21 Years of Traditional Art",
    "experienceYears": 21,
    "capacity": "45 pieces/month",
    "capacityPerMonth": 45,
    "fulfillmentDays": 11,
    "trustScore": 90,
    "rating": 4.8,
    "reviewCount": 134,
    "giCertified": true,
    "shgMember": true,
    "shgName": "Nirmal Karigar Samiti",
    "phone": "+91 94152 XXXXX",
    "email": "prakash.rao@karigarsetu.in",
    "bio": "Dedicated master craftsperson with 21 years preserving authentic Indian Painting & Wall Art traditions.",
    "verificationStatus": "Verified",
    "avatarUrl": "/images/avatars/artisan-052.svg",
    "aadhaarVerified": true,
    "bankAccountVerified": true,
    "skills": [
      "Painting & Wall Art",
      "Cluster GI Certified",
      "Fair Wage Standard",
      "Traditional Crafting"
    ],
    "certifications": [
      "GI Tag Certified (GI-AU-2019-2052)",
      "Ministry of Textiles Pehchan Card (TE-NIR-PAI-1052)",
      "All India Handicrafts Board Registered"
    ],
    "artisanId": "artisan-052",
    "isDemoData": true
  }
];
export type DemoArtisan = typeof DEMO_ARTISANS[0];
