export const DEMO_INQUIRIES = [
  {
    "id": "inquiry-001",
    "inquiryId": "inquiry-001",
    "artisanId": "artisan-001",
    "legacyArtisanId": "artisan-1",
    "artisanName": "Savita Devi",
    "productId": "product-001",
    "legacyProductId": "p1",
    "productName": "Hand-painted Madhubani Wall Art",
    "buyerId": "buyer-001",
    "buyerName": "Ananya Sharma",
    "buyerOrg": "Heritage Home Collective",
    "buyerCity": "New Delhi",
    "buyerState": "Delhi",
    "quantity": 15,
    "unitPrice": 2992,
    "totalAmount": 44880,
    "status": "New",
    "timeline": "Delivery within 12 days",
    "notes": "Wholesale sourcing inquiry for Hand-painted Madhubani Wall Art. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-002",
    "inquiryId": "inquiry-002",
    "artisanId": "artisan-002",
    "legacyArtisanId": "artisan-2",
    "artisanName": "Meena Kumari",
    "productId": "product-004",
    "legacyProductId": "p8",
    "productName": "Tribal Dokra Brass Elephant Figurine",
    "buyerId": "buyer-002",
    "buyerName": "Vikram Malhotra",
    "buyerOrg": "Urban Craft Retail",
    "buyerCity": "Mumbai",
    "buyerState": "Delhi",
    "quantity": 22,
    "unitPrice": 2328,
    "totalAmount": 51216,
    "status": "Negotiating",
    "timeline": "Delivery within 15 days",
    "notes": "Wholesale sourcing inquiry for Tribal Dokra Brass Elephant Figurine. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-003",
    "inquiryId": "inquiry-003",
    "artisanId": "artisan-003",
    "legacyArtisanId": "artisan-3",
    "artisanName": "Ramesh Kumar",
    "productId": "product-007",
    "legacyProductId": "p55",
    "productName": "Moradabadi Handcrafted Brass Peacock Diya Set",
    "buyerId": "buyer-003",
    "buyerName": "Kavita Nair",
    "buyerOrg": "Bharat Handloom House",
    "buyerCity": "Bengaluru",
    "buyerState": "Delhi",
    "quantity": 29,
    "unitPrice": 2232,
    "totalAmount": 64728,
    "status": "Confirmed",
    "timeline": "Delivery within 13 days",
    "notes": "Wholesale sourcing inquiry for Moradabadi Handcrafted Brass Peacock Diya Set. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-004",
    "inquiryId": "inquiry-004",
    "artisanId": "artisan-004",
    "legacyArtisanId": "artisan-4",
    "artisanName": "Mohan Das",
    "productId": "product-009",
    "legacyProductId": "p13",
    "productName": "Bankura Long-Neck Terracotta Horse",
    "buyerId": "buyer-004",
    "buyerName": "Gautam Mehta",
    "buyerOrg": "Earth & Loom Exports",
    "buyerCity": "Gujarat",
    "buyerState": "Delhi",
    "quantity": 36,
    "unitPrice": 1852,
    "totalAmount": 66672,
    "status": "Dispatched",
    "timeline": "Delivery within 13 days",
    "notes": "Wholesale sourcing inquiry for Bankura Long-Neck Terracotta Horse. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-005",
    "inquiryId": "inquiry-005",
    "artisanId": "artisan-005",
    "legacyArtisanId": "artisan-5",
    "artisanName": "Anjali Sahu",
    "productId": "product-011",
    "legacyProductId": "p11",
    "productName": "Sohrai Tribal Art Canvas",
    "buyerId": "buyer-005",
    "buyerName": "Priya Sundaram",
    "buyerOrg": "CraftBasket Wholesale",
    "buyerCity": "Chennai",
    "buyerState": "Delhi",
    "quantity": 43,
    "unitPrice": 3610,
    "totalAmount": 155230,
    "status": "Completed",
    "timeline": "Delivery within 19 days",
    "notes": "Wholesale sourcing inquiry for Sohrai Tribal Art Canvas. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-006",
    "inquiryId": "inquiry-006",
    "artisanId": "artisan-006",
    "legacyArtisanId": "artisan-6",
    "artisanName": "Arjun Sahu",
    "productId": "product-013",
    "legacyProductId": "p17",
    "productName": "Raghurajpur Pattachitra Dasavatara Scroll",
    "buyerId": "buyer-006",
    "buyerName": "Aditya Verma",
    "buyerOrg": "FolkRoots Lifestyle",
    "buyerCity": "Jaipur",
    "buyerState": "Delhi",
    "quantity": 50,
    "unitPrice": 17575,
    "totalAmount": 878750,
    "status": "New",
    "timeline": "Delivery within 20 days",
    "notes": "Wholesale sourcing inquiry for Raghurajpur Pattachitra Dasavatara Scroll. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-007",
    "inquiryId": "inquiry-007",
    "artisanId": "artisan-007",
    "legacyArtisanId": "artisan-7",
    "artisanName": "Pooja Mahato",
    "productId": "product-015",
    "legacyProductId": "p4",
    "productName": "Golden Sikki Grass Decorative Pauti Box",
    "buyerId": "buyer-007",
    "buyerName": "Rohan Mukherjee",
    "buyerOrg": "Studio Bharat Interio",
    "buyerCity": "Kolkata",
    "buyerState": "Delhi",
    "quantity": 57,
    "unitPrice": 1188,
    "totalAmount": 67716,
    "status": "Negotiating",
    "timeline": "Delivery within 12 days",
    "notes": "Wholesale sourcing inquiry for Golden Sikki Grass Decorative Pauti Box. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-008",
    "inquiryId": "inquiry-008",
    "artisanId": "artisan-008",
    "legacyArtisanId": "artisan-8",
    "artisanName": "Rajesh Mahato",
    "productId": "product-017",
    "legacyProductId": "p107",
    "productName": "Bastar Hand-Forged Wrought Iron Deer Figurine",
    "buyerId": "buyer-008",
    "buyerName": "Sneha Reddy",
    "buyerOrg": "Artisan Avenue Corp",
    "buyerCity": "Hyderabad",
    "buyerState": "Delhi",
    "quantity": 19,
    "unitPrice": 2042,
    "totalAmount": 38798,
    "status": "Confirmed",
    "timeline": "Delivery within 14 days",
    "notes": "Wholesale sourcing inquiry for Bastar Hand-Forged Wrought Iron Deer Figurine. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-009",
    "inquiryId": "inquiry-009",
    "artisanId": "artisan-009",
    "legacyArtisanId": "artisan-9",
    "artisanName": "Rekha Kumari",
    "productId": "product-019",
    "legacyProductId": "p15",
    "productName": "Kantha Stitch Tussar Silk Stole",
    "buyerId": "buyer-009",
    "buyerName": "Kabir Sengupta",
    "buyerOrg": "Rural Luxe Global",
    "buyerCity": "Haryana",
    "buyerState": "Delhi",
    "quantity": 26,
    "unitPrice": 3990,
    "totalAmount": 103740,
    "status": "Dispatched",
    "timeline": "Delivery within 17 days",
    "notes": "Wholesale sourcing inquiry for Kantha Stitch Tussar Silk Stole. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-010",
    "inquiryId": "inquiry-010",
    "artisanId": "artisan-010",
    "legacyArtisanId": "artisan-10",
    "artisanName": "Suresh Prasad",
    "productId": "product-021",
    "legacyProductId": "p21",
    "productName": "Cuttack Tarkasi Pure Silver Konark Wheel Brooch",
    "buyerId": "buyer-010",
    "buyerName": "Nandita Joshi",
    "buyerOrg": "Handmade Collective",
    "buyerCity": "Pune",
    "buyerState": "Delhi",
    "quantity": 33,
    "unitPrice": 3773,
    "totalAmount": 124509,
    "status": "Completed",
    "timeline": "Delivery within 13 days",
    "notes": "Wholesale sourcing inquiry for Cuttack Tarkasi Pure Silver Konark Wheel Brooch. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-011",
    "inquiryId": "inquiry-011",
    "artisanId": "artisan-011",
    "legacyArtisanId": "artisan-11",
    "artisanName": "Sunita Oraon",
    "productId": "product-023",
    "legacyProductId": "p23",
    "productName": "Bagru Dabu Mud-Resist Cotton Saree",
    "buyerId": "buyer-011",
    "buyerName": "Partner 11",
    "buyerOrg": "IndoCraft Enterprise #11",
    "buyerCity": "Sector 11",
    "buyerState": "Delhi",
    "quantity": 40,
    "unitPrice": 2518,
    "totalAmount": 100720,
    "status": "New",
    "timeline": "Delivery within 15 days",
    "notes": "Wholesale sourcing inquiry for Bagru Dabu Mud-Resist Cotton Saree. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-012",
    "inquiryId": "inquiry-012",
    "artisanId": "artisan-012",
    "legacyArtisanId": "artisan-12",
    "artisanName": "Deepak Oraon",
    "productId": "product-025",
    "legacyProductId": "p25",
    "productName": "Jaipur Blue Pottery Decorative Wall Plate",
    "buyerId": "buyer-012",
    "buyerName": "Partner 12",
    "buyerOrg": "IndoCraft Enterprise #12",
    "buyerCity": "Sector 12",
    "buyerState": "Delhi",
    "quantity": 47,
    "unitPrice": 1568,
    "totalAmount": 73696,
    "status": "Negotiating",
    "timeline": "Delivery within 11 days",
    "notes": "Wholesale sourcing inquiry for Jaipur Blue Pottery Decorative Wall Plate. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-013",
    "inquiryId": "inquiry-013",
    "artisanId": "artisan-013",
    "legacyArtisanId": "artisan-13",
    "artisanName": "Kavita Das",
    "productId": "product-027",
    "legacyProductId": "p6",
    "productName": "Khatwa Applique Hand-Stitched Cushion Covers",
    "buyerId": "buyer-013",
    "buyerName": "Partner 13",
    "buyerOrg": "IndoCraft Enterprise #13",
    "buyerCity": "Sector 13",
    "buyerState": "Delhi",
    "quantity": 54,
    "unitPrice": 1378,
    "totalAmount": 74412,
    "status": "Confirmed",
    "timeline": "Delivery within 17 days",
    "notes": "Wholesale sourcing inquiry for Khatwa Applique Hand-Stitched Cushion Covers. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-014",
    "inquiryId": "inquiry-014",
    "artisanId": "artisan-014",
    "legacyArtisanId": "artisan-14",
    "artisanName": "Manoj Das",
    "productId": "product-029",
    "legacyProductId": "p30",
    "productName": "Camel Leather Embroidered Mojari Jutti",
    "buyerId": "buyer-014",
    "buyerName": "Partner 14",
    "buyerOrg": "IndoCraft Enterprise #14",
    "buyerCity": "Sector 14",
    "buyerState": "Delhi",
    "quantity": 16,
    "unitPrice": 1568,
    "totalAmount": 25088,
    "status": "Dispatched",
    "timeline": "Delivery within 20 days",
    "notes": "Wholesale sourcing inquiry for Camel Leather Embroidered Mojari Jutti. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-015",
    "inquiryId": "inquiry-015",
    "artisanId": "artisan-015",
    "legacyArtisanId": "artisan-15",
    "artisanName": "Laxmi Pradhan",
    "productId": "product-031",
    "legacyProductId": "p32",
    "productName": "Nirona Rogan Castor-Oil Painted Stole",
    "buyerId": "buyer-015",
    "buyerName": "Partner 15",
    "buyerOrg": "IndoCraft Enterprise #15",
    "buyerCity": "Sector 15",
    "buyerState": "Delhi",
    "quantity": 23,
    "unitPrice": 7030,
    "totalAmount": 161690,
    "status": "Completed",
    "timeline": "Delivery within 15 days",
    "notes": "Wholesale sourcing inquiry for Nirona Rogan Castor-Oil Painted Stole. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-016",
    "inquiryId": "inquiry-016",
    "artisanId": "artisan-016",
    "legacyArtisanId": "artisan-16",
    "artisanName": "Bikash Pradhan",
    "productId": "product-033",
    "legacyProductId": "p34",
    "productName": "Bhujodi Kala Cotton Handwoven Shawl",
    "buyerId": "buyer-016",
    "buyerName": "Partner 16",
    "buyerOrg": "IndoCraft Enterprise #16",
    "buyerCity": "Sector 16",
    "buyerState": "Delhi",
    "quantity": 30,
    "unitPrice": 4560,
    "totalAmount": 136800,
    "status": "New",
    "timeline": "Delivery within 14 days",
    "notes": "Wholesale sourcing inquiry for Bhujodi Kala Cotton Handwoven Shawl. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-017",
    "inquiryId": "inquiry-017",
    "artisanId": "artisan-017",
    "legacyArtisanId": "artisan-17",
    "artisanName": "Rina Kumari",
    "productId": "product-035",
    "legacyProductId": "p36",
    "productName": "Jamnagar Pure Georgette Bandhani Dupatta",
    "buyerId": "buyer-017",
    "buyerName": "Partner 17",
    "buyerOrg": "IndoCraft Enterprise #17",
    "buyerCity": "Sector 17",
    "buyerState": "Delhi",
    "quantity": 37,
    "unitPrice": 3420,
    "totalAmount": 126540,
    "status": "Negotiating",
    "timeline": "Delivery within 11 days",
    "notes": "Wholesale sourcing inquiry for Jamnagar Pure Georgette Bandhani Dupatta. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-018",
    "inquiryId": "inquiry-018",
    "artisanId": "artisan-018",
    "legacyArtisanId": "artisan-18",
    "artisanName": "Amit Kumar",
    "productId": "product-037",
    "legacyProductId": "p38",
    "productName": "Polished Cambay Moss Agate Coaster Set",
    "buyerId": "buyer-018",
    "buyerName": "Partner 18",
    "buyerOrg": "IndoCraft Enterprise #18",
    "buyerCity": "Sector 18",
    "buyerState": "Delhi",
    "quantity": 44,
    "unitPrice": 1392,
    "totalAmount": 61248,
    "status": "Confirmed",
    "timeline": "Delivery within 12 days",
    "notes": "Wholesale sourcing inquiry for Polished Cambay Moss Agate Coaster Set. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-019",
    "inquiryId": "inquiry-019",
    "artisanId": "artisan-019",
    "legacyArtisanId": "artisan-19",
    "artisanName": "Shanti Devi",
    "productId": "product-039",
    "legacyProductId": "p40",
    "productName": "Chanderi Silk-Cotton Saree with Ashavali Border",
    "buyerId": "buyer-019",
    "buyerName": "Partner 19",
    "buyerOrg": "IndoCraft Enterprise #19",
    "buyerCity": "Sector 19",
    "buyerState": "Delhi",
    "quantity": 51,
    "unitPrice": 7410,
    "totalAmount": 377910,
    "status": "Dispatched",
    "timeline": "Delivery within 23 days",
    "notes": "Wholesale sourcing inquiry for Chanderi Silk-Cotton Saree with Ashavali Border. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-020",
    "inquiryId": "inquiry-020",
    "artisanId": "artisan-020",
    "legacyArtisanId": "artisan-20",
    "artisanName": "Sanjay Verma",
    "productId": "product-041",
    "legacyProductId": "p42",
    "productName": "Authentic Bagh Hand-Block Printed Cotton Bedcover",
    "buyerId": "buyer-020",
    "buyerName": "Partner 20",
    "buyerOrg": "IndoCraft Enterprise #20",
    "buyerCity": "Sector 20",
    "buyerState": "Delhi",
    "quantity": 58,
    "unitPrice": 2708,
    "totalAmount": 157064,
    "status": "Completed",
    "timeline": "Delivery within 13 days",
    "notes": "Wholesale sourcing inquiry for Authentic Bagh Hand-Block Printed Cotton Bedcover. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-021",
    "inquiryId": "inquiry-021",
    "artisanId": "artisan-021",
    "legacyArtisanId": "artisan-21",
    "artisanName": "Poonam Sahu",
    "productId": "product-043",
    "legacyProductId": "p44",
    "productName": "Gond Hand-Painted Canvas — Birds in Mahua Tree",
    "buyerId": "buyer-021",
    "buyerName": "Partner 21",
    "buyerOrg": "IndoCraft Enterprise #21",
    "buyerCity": "Sector 21",
    "buyerState": "Delhi",
    "quantity": 20,
    "unitPrice": 5130,
    "totalAmount": 102600,
    "status": "New",
    "timeline": "Delivery within 19 days",
    "notes": "Wholesale sourcing inquiry for Gond Hand-Painted Canvas — Birds in Mahua Tree. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-022",
    "inquiryId": "inquiry-022",
    "artisanId": "artisan-022",
    "legacyArtisanId": "artisan-22",
    "artisanName": "Dhaniram Kashyap",
    "productId": "product-045",
    "legacyProductId": "p46",
    "productName": "Tikamgarh Bell Metal Gauri-Shankar Diya",
    "buyerId": "buyer-022",
    "buyerName": "Partner 22",
    "buyerOrg": "IndoCraft Enterprise #22",
    "buyerCity": "Sector 22",
    "buyerState": "Delhi",
    "quantity": 27,
    "unitPrice": 2612,
    "totalAmount": 70524,
    "status": "Negotiating",
    "timeline": "Delivery within 14 days",
    "notes": "Wholesale sourcing inquiry for Tikamgarh Bell Metal Gauri-Shankar Diya. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-023",
    "inquiryId": "inquiry-023",
    "artisanId": "artisan-023",
    "legacyArtisanId": "artisan-23",
    "artisanName": "Champa Ben",
    "productId": "product-047",
    "legacyProductId": "p48",
    "productName": "Pure Katan Silk Banarasi Saree with Kadwa Zari",
    "buyerId": "buyer-023",
    "buyerName": "Partner 23",
    "buyerOrg": "IndoCraft Enterprise #23",
    "buyerCity": "Sector 23",
    "buyerState": "Delhi",
    "quantity": 34,
    "unitPrice": 27075,
    "totalAmount": 920550,
    "status": "Confirmed",
    "timeline": "Delivery within 21 days",
    "notes": "Wholesale sourcing inquiry for Pure Katan Silk Banarasi Saree with Kadwa Zari. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-024",
    "inquiryId": "inquiry-024",
    "artisanId": "artisan-024",
    "legacyArtisanId": "artisan-24",
    "artisanName": "Prem Chand",
    "productId": "product-049",
    "legacyProductId": "p51",
    "productName": "Khurja Hand-Painted Ceramic Chai Cup & Saucer Set",
    "buyerId": "buyer-024",
    "buyerName": "Partner 24",
    "buyerOrg": "IndoCraft Enterprise #24",
    "buyerCity": "Sector 24",
    "buyerState": "Delhi",
    "quantity": 41,
    "unitPrice": 922,
    "totalAmount": 37802,
    "status": "Dispatched",
    "timeline": "Delivery within 16 days",
    "notes": "Wholesale sourcing inquiry for Khurja Hand-Painted Ceramic Chai Cup & Saucer Set. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-025",
    "inquiryId": "inquiry-025",
    "artisanId": "artisan-025",
    "legacyArtisanId": "artisan-25",
    "artisanName": "Sunita Negi",
    "productId": "product-051",
    "legacyProductId": "p53",
    "productName": "Lucknowi Hand-Embroidered Mulmul Kurta",
    "buyerId": "buyer-025",
    "buyerName": "Partner 25",
    "buyerOrg": "IndoCraft Enterprise #25",
    "buyerCity": "Sector 25",
    "buyerState": "Delhi",
    "quantity": 48,
    "unitPrice": 3312,
    "totalAmount": 158976,
    "status": "Completed",
    "timeline": "Delivery within 13 days",
    "notes": "Wholesale sourcing inquiry for Lucknowi Hand-Embroidered Mulmul Kurta. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-026",
    "inquiryId": "inquiry-026",
    "artisanId": "artisan-026",
    "legacyArtisanId": "artisan-26",
    "artisanName": "Vijay Kumar Rastogi",
    "productId": "product-053",
    "legacyProductId": "p58",
    "productName": "Sheesham Wood Jali Coaster Set with Holder",
    "buyerId": "buyer-026",
    "buyerName": "Partner 26",
    "buyerOrg": "IndoCraft Enterprise #26",
    "buyerCity": "Sector 26",
    "buyerState": "Delhi",
    "quantity": 55,
    "unitPrice": 428,
    "totalAmount": 23540,
    "status": "New",
    "timeline": "Delivery within 11 days",
    "notes": "Wholesale sourcing inquiry for Sheesham Wood Jali Coaster Set with Holder. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-027",
    "inquiryId": "inquiry-027",
    "artisanId": "artisan-027",
    "legacyArtisanId": "artisan-27",
    "artisanName": "Padmawati Amma",
    "productId": "product-054",
    "legacyProductId": "p57",
    "productName": "Saharanpur Sheesham Wood Folding Screen",
    "buyerId": "buyer-027",
    "buyerName": "Partner 27",
    "buyerOrg": "IndoCraft Enterprise #27",
    "buyerCity": "Sector 27",
    "buyerState": "Delhi",
    "quantity": 17,
    "unitPrice": 13775,
    "totalAmount": 234175,
    "status": "Negotiating",
    "timeline": "Delivery within 19 days",
    "notes": "Wholesale sourcing inquiry for Saharanpur Sheesham Wood Folding Screen. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-028",
    "inquiryId": "inquiry-028",
    "artisanId": "artisan-028",
    "legacyArtisanId": "artisan-28",
    "artisanName": "Nirmala Devi",
    "productId": "product-055",
    "legacyProductId": "p59",
    "productName": "Kumaoni Traditional Aipan Art Wooden Pooja Chowki",
    "buyerId": "buyer-028",
    "buyerName": "Partner 28",
    "buyerOrg": "IndoCraft Enterprise #28",
    "buyerCity": "Sector 28",
    "buyerState": "Delhi",
    "quantity": 24,
    "unitPrice": 1662,
    "totalAmount": 39888,
    "status": "Confirmed",
    "timeline": "Delivery within 13 days",
    "notes": "Wholesale sourcing inquiry for Kumaoni Traditional Aipan Art Wooden Pooja Chowki. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-029",
    "inquiryId": "inquiry-029",
    "artisanId": "artisan-029",
    "legacyArtisanId": "artisan-29",
    "artisanName": "Radha Bai",
    "productId": "product-057",
    "legacyProductId": "p61",
    "productName": "Kullu Pure Merino Wool Shawl",
    "buyerId": "buyer-029",
    "buyerName": "Partner 29",
    "buyerOrg": "IndoCraft Enterprise #29",
    "buyerCity": "Sector 29",
    "buyerState": "Delhi",
    "quantity": 31,
    "unitPrice": 3420,
    "totalAmount": 106020,
    "status": "Dispatched",
    "timeline": "Delivery within 14 days",
    "notes": "Wholesale sourcing inquiry for Kullu Pure Merino Wool Shawl. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-030",
    "inquiryId": "inquiry-030",
    "artisanId": "artisan-030",
    "legacyArtisanId": "artisan-30",
    "artisanName": "Lata Devi",
    "productId": "product-059",
    "legacyProductId": "p63",
    "productName": "Kashmiri Hand-Carved Walnut Wood Box",
    "buyerId": "buyer-030",
    "buyerName": "Partner 30",
    "buyerOrg": "IndoCraft Enterprise #30",
    "buyerCity": "Sector 30",
    "buyerState": "Delhi",
    "quantity": 38,
    "unitPrice": 4418,
    "totalAmount": 167884,
    "status": "Completed",
    "timeline": "Delivery within 15 days",
    "notes": "Wholesale sourcing inquiry for Kashmiri Hand-Carved Walnut Wood Box. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-031",
    "inquiryId": "inquiry-031",
    "artisanId": "artisan-031",
    "legacyArtisanId": "artisan-31",
    "artisanName": "Sumitra Roy",
    "productId": "product-061",
    "legacyProductId": "p65",
    "productName": "Pure Kashmiri Pashmina Shawl with Sozni Needlework",
    "buyerId": "buyer-031",
    "buyerName": "Partner 31",
    "buyerOrg": "IndoCraft Enterprise #31",
    "buyerCity": "Sector 31",
    "buyerState": "Delhi",
    "quantity": 45,
    "unitPrice": 25970,
    "totalAmount": 1168650,
    "status": "New",
    "timeline": "Delivery within 16 days",
    "notes": "Wholesale sourcing inquiry for Pure Kashmiri Pashmina Shawl with Sozni Needlework. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-032",
    "inquiryId": "inquiry-032",
    "artisanId": "artisan-032",
    "legacyArtisanId": "artisan-32",
    "artisanName": "Kamala Das",
    "productId": "product-063",
    "legacyProductId": "p67",
    "productName": "Kashmiri Papier-Mâché Trinket Box with 24K Gold",
    "buyerId": "buyer-032",
    "buyerName": "Partner 32",
    "buyerOrg": "IndoCraft Enterprise #32",
    "buyerCity": "Sector 32",
    "buyerState": "Delhi",
    "quantity": 52,
    "unitPrice": 1758,
    "totalAmount": 91416,
    "status": "Negotiating",
    "timeline": "Delivery within 17 days",
    "notes": "Wholesale sourcing inquiry for Kashmiri Papier-Mâché Trinket Box with 24K Gold. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-033",
    "inquiryId": "inquiry-033",
    "artisanId": "artisan-033",
    "legacyArtisanId": "artisan-33",
    "artisanName": "Urmila Soni",
    "productId": "product-065",
    "legacyProductId": "p69",
    "productName": "Traditional Bagh Phulkari Georgette Dupatta",
    "buyerId": "buyer-001",
    "buyerName": "Ananya Sharma",
    "buyerOrg": "Heritage Home Collective",
    "buyerCity": "New Delhi",
    "buyerState": "Delhi",
    "quantity": 59,
    "unitPrice": 4704,
    "totalAmount": 277536,
    "status": "Confirmed",
    "timeline": "Delivery within 18 days",
    "notes": "Wholesale sourcing inquiry for Traditional Bagh Phulkari Georgette Dupatta. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-034",
    "inquiryId": "inquiry-034",
    "artisanId": "artisan-034",
    "legacyArtisanId": "artisan-34",
    "artisanName": "Bimala Soren",
    "productId": "product-067",
    "legacyProductId": "p71",
    "productName": "Hand-Thrown Earthen Water Matka with Brass Spigot",
    "buyerId": "buyer-002",
    "buyerName": "Vikram Malhotra",
    "buyerOrg": "Urban Craft Retail",
    "buyerCity": "Mumbai",
    "buyerState": "Delhi",
    "quantity": 21,
    "unitPrice": 808,
    "totalAmount": 16968,
    "status": "Dispatched",
    "timeline": "Delivery within 19 days",
    "notes": "Wholesale sourcing inquiry for Hand-Thrown Earthen Water Matka with Brass Spigot. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-035",
    "inquiryId": "inquiry-035",
    "artisanId": "artisan-035",
    "legacyArtisanId": "artisan-35",
    "artisanName": "Shalini Reddy",
    "productId": "product-069",
    "legacyProductId": "p73",
    "productName": "Warli Tarpa Dance Folk Painting on Canvas",
    "buyerId": "buyer-003",
    "buyerName": "Kavita Nair",
    "buyerOrg": "Bharat Handloom House",
    "buyerCity": "Bengaluru",
    "buyerState": "Delhi",
    "quantity": 28,
    "unitPrice": 2755,
    "totalAmount": 77140,
    "status": "Completed",
    "timeline": "Delivery within 13 days",
    "notes": "Wholesale sourcing inquiry for Warli Tarpa Dance Folk Painting on Canvas. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-036",
    "inquiryId": "inquiry-036",
    "artisanId": "artisan-036",
    "legacyArtisanId": "artisan-36",
    "artisanName": "Devika Rani",
    "productId": "product-071",
    "legacyProductId": "p75",
    "productName": "Vegetable-Tanned Leather Kolhapuri Chappal",
    "buyerId": "buyer-004",
    "buyerName": "Gautam Mehta",
    "buyerOrg": "Earth & Loom Exports",
    "buyerCity": "Gujarat",
    "buyerState": "Delhi",
    "quantity": 35,
    "unitPrice": 1662,
    "totalAmount": 58170,
    "status": "New",
    "timeline": "Delivery within 14 days",
    "notes": "Wholesale sourcing inquiry for Vegetable-Tanned Leather Kolhapuri Chappal. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-037",
    "inquiryId": "inquiry-037",
    "artisanId": "artisan-037",
    "legacyArtisanId": "artisan-37",
    "artisanName": "Hema Malini Sahu",
    "productId": "product-073",
    "legacyProductId": "p77",
    "productName": "Yeola Pure Silk Paithani Saree with Mor Pallu",
    "buyerId": "buyer-005",
    "buyerName": "Priya Sundaram",
    "buyerOrg": "CraftBasket Wholesale",
    "buyerCity": "Chennai",
    "buyerState": "Delhi",
    "quantity": 42,
    "unitPrice": 22800,
    "totalAmount": 957600,
    "status": "Negotiating",
    "timeline": "Delivery within 15 days",
    "notes": "Wholesale sourcing inquiry for Yeola Pure Silk Paithani Saree with Mor Pallu. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-038",
    "inquiryId": "inquiry-038",
    "artisanId": "artisan-038",
    "legacyArtisanId": "artisan-38",
    "artisanName": "Pushpa Bai",
    "productId": "product-075",
    "legacyProductId": "p79",
    "productName": "Polished Coconut Shell Breakfast Bowls Set",
    "buyerId": "buyer-006",
    "buyerName": "Aditya Verma",
    "buyerOrg": "FolkRoots Lifestyle",
    "buyerCity": "Jaipur",
    "buyerState": "Delhi",
    "quantity": 49,
    "unitPrice": 684,
    "totalAmount": 33516,
    "status": "Confirmed",
    "timeline": "Delivery within 16 days",
    "notes": "Wholesale sourcing inquiry for Polished Coconut Shell Breakfast Bowls Set. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-039",
    "inquiryId": "inquiry-039",
    "artisanId": "artisan-039",
    "legacyArtisanId": "artisan-39",
    "artisanName": "Geeta Ben",
    "productId": "product-077",
    "legacyProductId": "p81",
    "productName": "Mysore Rosewood Inlay Wall Art Panel",
    "buyerId": "buyer-007",
    "buyerName": "Rohan Mukherjee",
    "buyerOrg": "Studio Bharat Interio",
    "buyerCity": "Kolkata",
    "buyerState": "Delhi",
    "quantity": 56,
    "unitPrice": 8428,
    "totalAmount": 471968,
    "status": "Dispatched",
    "timeline": "Delivery within 17 days",
    "notes": "Wholesale sourcing inquiry for Mysore Rosewood Inlay Wall Art Panel. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-040",
    "inquiryId": "inquiry-040",
    "artisanId": "artisan-040",
    "legacyArtisanId": "artisan-40",
    "artisanName": "Gopal Krishna",
    "productId": "product-079",
    "legacyProductId": "p83",
    "productName": "Handcrafted Kinhal Painted Wooden Cow & Calf",
    "buyerId": "buyer-008",
    "buyerName": "Sneha Reddy",
    "buyerOrg": "Artisan Avenue Corp",
    "buyerCity": "Hyderabad",
    "buyerState": "Delhi",
    "quantity": 18,
    "unitPrice": 1995,
    "totalAmount": 35910,
    "status": "Completed",
    "timeline": "Delivery within 18 days",
    "notes": "Wholesale sourcing inquiry for Handcrafted Kinhal Painted Wooden Cow & Calf. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-041",
    "inquiryId": "inquiry-041",
    "artisanId": "artisan-041",
    "legacyArtisanId": "artisan-41",
    "artisanName": "Brij Mohan",
    "productId": "product-081",
    "legacyProductId": "p85",
    "productName": "Authentic Aranmula Kannadi Handcrafted Metal Mirror",
    "buyerId": "buyer-009",
    "buyerName": "Kabir Sengupta",
    "buyerOrg": "Rural Luxe Global",
    "buyerCity": "Haryana",
    "buyerState": "Delhi",
    "quantity": 25,
    "unitPrice": 21070,
    "totalAmount": 526750,
    "status": "New",
    "timeline": "Delivery within 19 days",
    "notes": "Wholesale sourcing inquiry for Authentic Aranmula Kannadi Handcrafted Metal Mirror. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-042",
    "inquiryId": "inquiry-042",
    "artisanId": "artisan-042",
    "legacyArtisanId": "artisan-42",
    "artisanName": "Tsering Dorje",
    "productId": "product-083",
    "legacyProductId": "p87",
    "productName": "Balaramapuram Kasavu Cotton Saree Gold Zari",
    "buyerId": "buyer-010",
    "buyerName": "Nandita Joshi",
    "buyerOrg": "Handmade Collective",
    "buyerCity": "Pune",
    "buyerState": "Delhi",
    "quantity": 32,
    "unitPrice": 3040,
    "totalAmount": 97280,
    "status": "Negotiating",
    "timeline": "Delivery within 13 days",
    "notes": "Wholesale sourcing inquiry for Balaramapuram Kasavu Cotton Saree Gold Zari. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-043",
    "inquiryId": "inquiry-043",
    "artisanId": "artisan-043",
    "legacyArtisanId": "artisan-43",
    "artisanName": "Abdul Ghani",
    "productId": "product-085",
    "legacyProductId": "p89",
    "productName": "Heirloom Pure Silk Kanchipuram Saree with Pure Zari",
    "buyerId": "buyer-011",
    "buyerName": "Partner 11",
    "buyerOrg": "IndoCraft Enterprise #11",
    "buyerCity": "Sector 11",
    "buyerState": "Delhi",
    "quantity": 39,
    "unitPrice": 30400,
    "totalAmount": 1185600,
    "status": "Confirmed",
    "timeline": "Delivery within 14 days",
    "notes": "Wholesale sourcing inquiry for Heirloom Pure Silk Kanchipuram Saree with Pure Zari. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-044",
    "inquiryId": "inquiry-044",
    "artisanId": "artisan-044",
    "legacyArtisanId": "artisan-44",
    "artisanName": "Naveen Babu",
    "productId": "product-087",
    "legacyProductId": "p91",
    "productName": "Swamimalai Bronze Nataraja Icon (15-inch, Panchaloha)",
    "buyerId": "buyer-012",
    "buyerName": "Partner 12",
    "buyerOrg": "IndoCraft Enterprise #12",
    "buyerCity": "Sector 12",
    "buyerState": "Delhi",
    "quantity": 46,
    "unitPrice": 34200,
    "totalAmount": 1573200,
    "status": "Dispatched",
    "timeline": "Delivery within 15 days",
    "notes": "Wholesale sourcing inquiry for Swamimalai Bronze Nataraja Icon (15-inch, Panchaloha). Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-045",
    "inquiryId": "inquiry-045",
    "artisanId": "artisan-045",
    "legacyArtisanId": "artisan-45",
    "artisanName": "Krishnamurthy",
    "productId": "product-089",
    "legacyProductId": "p93",
    "productName": "Block Printed Kalamkari Cotton Bedspread",
    "buyerId": "buyer-013",
    "buyerName": "Partner 13",
    "buyerOrg": "IndoCraft Enterprise #13",
    "buyerCity": "Sector 13",
    "buyerState": "Delhi",
    "quantity": 53,
    "unitPrice": 2612,
    "totalAmount": 138436,
    "status": "Completed",
    "timeline": "Delivery within 16 days",
    "notes": "Wholesale sourcing inquiry for Block Printed Kalamkari Cotton Bedspread. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-046",
    "inquiryId": "inquiry-046",
    "artisanId": "artisan-046",
    "legacyArtisanId": "artisan-46",
    "artisanName": "Baldev Singh",
    "productId": "product-091",
    "legacyProductId": "p95",
    "productName": "Etikoppaka Non-Toxic Lacquered Wooden Spinning Tops Set",
    "buyerId": "buyer-014",
    "buyerName": "Partner 14",
    "buyerOrg": "IndoCraft Enterprise #14",
    "buyerCity": "Sector 14",
    "buyerState": "Delhi",
    "quantity": 15,
    "unitPrice": 365,
    "totalAmount": 5475,
    "status": "New",
    "timeline": "Delivery within 17 days",
    "notes": "Wholesale sourcing inquiry for Etikoppaka Non-Toxic Lacquered Wooden Spinning Tops Set. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-047",
    "inquiryId": "inquiry-047",
    "artisanId": "artisan-047",
    "legacyArtisanId": "artisan-47",
    "artisanName": "Manabendra Nath",
    "productId": "product-093",
    "legacyProductId": "p97",
    "productName": "Pochampally Double Ikat Silk Saree",
    "buyerId": "buyer-015",
    "buyerName": "Partner 15",
    "buyerOrg": "IndoCraft Enterprise #15",
    "buyerCity": "Sector 15",
    "buyerState": "Delhi",
    "quantity": 22,
    "unitPrice": 12825,
    "totalAmount": 282150,
    "status": "Negotiating",
    "timeline": "Delivery within 18 days",
    "notes": "Wholesale sourcing inquiry for Pochampally Double Ikat Silk Saree. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-048",
    "inquiryId": "inquiry-048",
    "artisanId": "artisan-048",
    "legacyArtisanId": "artisan-48",
    "artisanName": "Chenna Keshav",
    "productId": "product-095",
    "legacyProductId": "p99",
    "productName": "Assam Golden Muga Silk Mekhela Chador",
    "buyerId": "buyer-016",
    "buyerName": "Partner 16",
    "buyerOrg": "IndoCraft Enterprise #16",
    "buyerCity": "Sector 16",
    "buyerState": "Delhi",
    "quantity": 29,
    "unitPrice": 28025,
    "totalAmount": 812725,
    "status": "Confirmed",
    "timeline": "Delivery within 19 days",
    "notes": "Wholesale sourcing inquiry for Assam Golden Muga Silk Mekhela Chador. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-049",
    "inquiryId": "inquiry-049",
    "artisanId": "artisan-049",
    "legacyArtisanId": "artisan-49",
    "artisanName": "Ratan Lal",
    "productId": "product-097",
    "legacyProductId": "p101",
    "productName": "Tripura Bamboo Fine-Weave Fruit Basket",
    "buyerId": "buyer-017",
    "buyerName": "Partner 17",
    "buyerOrg": "IndoCraft Enterprise #17",
    "buyerCity": "Sector 17",
    "buyerState": "Delhi",
    "quantity": 36,
    "unitPrice": 589,
    "totalAmount": 21204,
    "status": "Dispatched",
    "timeline": "Delivery within 13 days",
    "notes": "Wholesale sourcing inquiry for Tripura Bamboo Fine-Weave Fruit Basket. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-050",
    "inquiryId": "inquiry-050",
    "artisanId": "artisan-050",
    "legacyArtisanId": "artisan-50",
    "artisanName": "Harishankar",
    "productId": "product-099",
    "legacyProductId": "p103",
    "productName": "Hand-Braided Kauna Water Reed Picnic Tote Bag",
    "buyerId": "buyer-018",
    "buyerName": "Partner 18",
    "buyerOrg": "IndoCraft Enterprise #18",
    "buyerCity": "Sector 18",
    "buyerState": "Delhi",
    "quantity": 43,
    "unitPrice": 1188,
    "totalAmount": 51084,
    "status": "Completed",
    "timeline": "Delivery within 14 days",
    "notes": "Wholesale sourcing inquiry for Hand-Braided Kauna Water Reed Picnic Tote Bag. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-051",
    "inquiryId": "inquiry-051",
    "artisanId": "artisan-051",
    "legacyArtisanId": "artisan-51",
    "artisanName": "Tenzin Norbu",
    "productId": "product-101",
    "legacyProductId": "p105",
    "productName": "Hand-Carved Naga Hardwood Ceremonial Horn Cup",
    "buyerId": "buyer-019",
    "buyerName": "Partner 19",
    "buyerOrg": "IndoCraft Enterprise #19",
    "buyerCity": "Sector 19",
    "buyerState": "Delhi",
    "quantity": 50,
    "unitPrice": 1662,
    "totalAmount": 83100,
    "status": "New",
    "timeline": "Delivery within 15 days",
    "notes": "Wholesale sourcing inquiry for Hand-Carved Naga Hardwood Ceremonial Horn Cup. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  },
  {
    "id": "inquiry-052",
    "inquiryId": "inquiry-052",
    "artisanId": "artisan-052",
    "legacyArtisanId": "artisan-52",
    "artisanName": "Prakash Rao",
    "productId": "product-103",
    "legacyProductId": "p19",
    "productName": "Sambalpuri Bandha Ikat Pure Silk Saree",
    "buyerId": "buyer-020",
    "buyerName": "Partner 20",
    "buyerOrg": "IndoCraft Enterprise #20",
    "buyerCity": "Sector 20",
    "buyerState": "Delhi",
    "quantity": 57,
    "unitPrice": 12160,
    "totalAmount": 693120,
    "status": "Negotiating",
    "timeline": "Delivery within 16 days",
    "notes": "Wholesale sourcing inquiry for Sambalpuri Bandha Ikat Pure Silk Saree. Requesting GI Tag origin certificates and sample batch for inspection.",
    "createdAt": "2026-09-08T10:00:00Z",
    "isDemoData": true
  }
];
export type DemoInquiry = typeof DEMO_INQUIRIES[0];
